import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  writeBrainWorkspace,
  BrainWriterError,
  MANIFEST_OUTPUT_PATH,
} from '../src/workspace/writer.js';
import { planBrainWorkspace } from '../src/workspace/orchestrator.js';
import { validateBrainWorkspace } from '../src/workspace/validator.js';
import { discoverWorkspaceState } from '../src/workspace/discover.js';
import { collectContextPackageState } from '../src/workspace/context-packages.js';
import { stableStringify } from '../src/context/fingerprint.js';
import { makeSnapshot, ENGINE_VERSION } from './brain-fixtures.js';
import { REPO_ROOT, cleanup } from './helpers.js';

const MARKER = '_Generated by DDAE. Derived from Docs/ and Git. Do not edit directly._';
const MISSING_STATE = {
  availability: 'missing', status: null, reasons: [], schema_version: null, engine_version: null,
  goal_hash: null, budget: null, fingerprint: null, counts: null, relevant_files: [],
};

const view = (title, body = '') => `# ${title}\n\n${MARKER}\n${body}`;
const file = (name, body) => ({ path: `DDAE-Brain/${name}`, content: view(name.replace(/\.md$/, ''), body) });
const SMALL_MANIFEST = Object.freeze({ schema_version: 'brain-manifest-v1', note: 'synthetic' });
const smallPlan = (names = ['Home.md', 'Sessions.md']) => ({ manifest: SMALL_MANIFEST, files: names.map((n) => file(n)) });
const realPlan = () => planBrainWorkspace({ snapshot: makeSnapshot(), contextPackageState: MISSING_STATE, engineVersion: ENGINE_VERSION });

/** outer/{project,outside}; `outside` holds a sentinel that must never change. */
function makeProject() {
  const outer = fs.mkdtempSync(path.join(os.tmpdir(), 'ddae-writer-test-'));
  const root = path.join(outer, 'project');
  const outside = path.join(outer, 'outside');
  fs.mkdirSync(root);
  fs.mkdirSync(outside);
  fs.writeFileSync(path.join(outside, 'sentinel.txt'), 'untouched', 'utf8');
  return { outer, root, outside };
}

function withProject(fn) {
  const project = makeProject();
  try {
    return fn(project);
  } finally {
    cleanup(project.outer);
  }
}

function tree(dir, base = dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const abs = path.join(dir, entry.name);
    const rel = path.relative(base, abs).split(path.sep).join('/');
    return entry.isDirectory() ? [`${rel}/`, ...tree(abs, base)] : [rel];
  }).sort();
}

const read = (root, rel) => fs.readFileSync(path.join(root, ...rel.split('/')), 'utf8');
const errorOf = (fn) => {
  try {
    fn();
  } catch (error) {
    assert.ok(error instanceof BrainWriterError, `expected BrainWriterError, got ${error?.constructor?.name}: ${error?.message}`);
    return error;
  }
  assert.fail('expected a BrainWriterError');
  return null;
};

function trySymlink(target, linkPath, type) {
  try {
    fs.symlinkSync(target, linkPath, type);
    return true;
  } catch {
    return false;
  }
}

function patchFs(name, replacement) {
  const original = fs[name];
  fs[name] = replacement(original);
  return () => { fs[name] = original; };
}

// ───────────────────────── A. API / happy path ─────────────────────────

test('A1. exports the expected API', () => {
  assert.equal(typeof writeBrainWorkspace, 'function');
  assert.equal(MANIFEST_OUTPUT_PATH, '.ddae/brain/manifest.json');
  const error = new BrainWriterError('X', 'm');
  assert.ok(error instanceof Error);
  assert.equal(error.code, 'X');
});

test('A2. an empty project receives every view and the manifest; directories are created; bytes equal the plan', () => {
  withProject(({ root }) => {
    const plan = realPlan();
    const report = writeBrainWorkspace(root, plan);
    assert.equal(report.written.length, plan.files.length + 1);
    for (const entry of plan.files) {
      assert.equal(read(root, entry.path), entry.content, entry.path);
    }
    assert.deepEqual(tree(root), [
      '.ddae/', '.ddae/brain/', '.ddae/brain/manifest.json',
      'DDAE-Brain/', ...plan.files.map((f) => f.path),
    ].sort());
  });
});

test('A3. the manifest is serialized with the canonical stableStringify plus exactly one final LF — no generated_at, no CRLF', () => {
  withProject(({ root }) => {
    const plan = realPlan();
    writeBrainWorkspace(root, plan);
    const text = read(root, MANIFEST_OUTPUT_PATH);
    assert.equal(text, `${stableStringify(plan.manifest)}\n`);
    assert.ok(!text.includes('\r') && !text.endsWith('\n\n') && !text.includes('generated_at'));
    assert.deepEqual(JSON.parse(text), JSON.parse(JSON.stringify(plan.manifest)));
  });
});

test('A4. the report lists relative forward-slash paths, sorted, frozen, without any content', () => {
  withProject(({ root }) => {
    const report = writeBrainWorkspace(root, smallPlan());
    assert.deepEqual([...report.written], ['.ddae/brain/manifest.json', 'DDAE-Brain/Home.md', 'DDAE-Brain/Sessions.md']);
    assert.deepEqual([...report.unchanged], []);
    assert.deepEqual([...report.stale_generated], []);
    assert.ok(Object.isFrozen(report) && Object.isFrozen(report.written) && Object.isFrozen(report.unchanged) && Object.isFrozen(report.stale_generated));
    assert.deepEqual(Object.keys(report).sort(), ['stale_generated', 'unchanged', 'written']);
    assert.ok(!JSON.stringify(report).includes(MARKER));
    assert.ok(!JSON.stringify(report).includes(root));
  });
});

test('A5. round trip: what the Writer materialises validates as VALID and equals the plan (real Orchestrator plan)', () => {
  withProject(({ root }) => {
    const plan = realPlan();
    writeBrainWorkspace(root, plan);
    const stored = JSON.parse(read(root, MANIFEST_OUTPUT_PATH));
    assert.deepEqual(validateBrainWorkspace(stored, { expectedViews: plan.files.map((f) => f.path) }), { status: 'VALID', reasons: [] });
  });
});

test('A6. self-host: the real repository plan is materialised into a temporary project only', () => {
  withProject(({ root }) => {
    const plan = planBrainWorkspace({
      snapshot: discoverWorkspaceState(REPO_ROOT),
      contextPackageState: collectContextPackageState(REPO_ROOT),
      engineVersion: ENGINE_VERSION,
    });
    const report = writeBrainWorkspace(root, plan);
    assert.equal(report.written.length, 9);
    assert.equal(validateBrainWorkspace(JSON.parse(read(root, MANIFEST_OUTPUT_PATH)), { expectedViews: plan.files.map((f) => f.path) }).status, 'VALID');
  });
  assert.ok(!fs.existsSync(path.join(REPO_ROOT, 'DDAE-Brain')));
  assert.ok(!fs.existsSync(path.join(REPO_ROOT, '.ddae', 'brain')));
});

test('A7. nothing but DDAE-Brain/*.md and .ddae/brain/manifest.json is ever created (no .gitignore, .obsidian, validation.json)', () => {
  withProject(({ root }) => {
    writeBrainWorkspace(root, smallPlan());
    const created = tree(root).filter((entry) => !entry.endsWith('/'));
    assert.deepEqual(created, ['.ddae/brain/manifest.json', 'DDAE-Brain/Home.md', 'DDAE-Brain/Sessions.md']);
  });
});

test('A8. an empty file list still materialises the manifest (a plan with no views is legal input)', () => {
  withProject(({ root }) => {
    const report = writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files: [] });
    assert.deepEqual([...report.written], ['.ddae/brain/manifest.json']);
  });
});

// ───────────────────────── input / root ─────────────────────────

test('I1. malformed input is rejected as INPUT_INVALID before anything is written', () => {
  withProject(({ root }) => {
    for (const bad of [undefined, null, 'x', [], {}, { manifest: null, files: [] }, { manifest: [], files: [] }, { manifest: SMALL_MANIFEST }, { manifest: SMALL_MANIFEST, files: 'x' }, { manifest: SMALL_MANIFEST, files: [null] }, { manifest: SMALL_MANIFEST, files: [{ path: 1, content: 'x' }] }]) {
      assert.equal(errorOf(() => writeBrainWorkspace(root, bad)).code, 'INPUT_INVALID', JSON.stringify(bad));
    }
    assert.equal(errorOf(() => writeBrainWorkspace(root, smallPlan(), { force: 'yes' })).code, 'INPUT_INVALID');
    assert.deepEqual(tree(root), []);
  });
});

test('R1. a missing or non-directory project root is PROJECT_ROOT_INVALID and is never created', () => {
  withProject(({ outer, root }) => {
    const missing = path.join(outer, 'does-not-exist');
    assert.equal(errorOf(() => writeBrainWorkspace(missing, smallPlan())).code, 'PROJECT_ROOT_INVALID');
    assert.ok(!fs.existsSync(missing));
    const asFile = path.join(outer, 'a-file');
    fs.writeFileSync(asFile, 'x');
    assert.equal(errorOf(() => writeBrainWorkspace(asFile, smallPlan())).code, 'PROJECT_ROOT_INVALID');
    for (const bad of [undefined, null, '', 42]) {
      assert.equal(errorOf(() => writeBrainWorkspace(bad, smallPlan())).code, 'PROJECT_ROOT_INVALID');
    }
    assert.deepEqual(tree(root), []);
  });
});

test('R2. errors and reports never expose the absolute project root', () => {
  withProject(({ root }) => {
    const error = errorOf(() => writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files: [{ path: '../x.md', content: 'x' }] }));
    assert.ok(!JSON.stringify(error.details).includes(root));
    assert.ok(!error.message.includes(root));
  });
});

// ───────────────────────── B/C. path grammar & characters ─────────────────────────

const BAD_PATHS = [
  '../x.md', 'DDAE-Brain/../x.md', 'DDAE-Brain/../../x.md', 'DDAE-Brain/./x.md', '/abs/x.md', '/DDAE-Brain/x.md',
  'C:/x.md', 'C:\\x.md', 'c:/DDAE-Brain/x.md', 'DDAE-Brain\\x.md', 'DDAE-Brain/a\\b.md',
  'http://example.com/x.md', 'file:///etc/x.md', 'javascript:alert(1)', 'DDAE-Brain/sub/x.md', 'DDAE-Brain/x.txt', 'DDAE-Brain/x.md.exe',
  'DDAE-Brain/.md', 'DDAE-Brain/', 'DDAE-Brain', '', 'x.md', 'Docs/x.md', '.ddae/brain/other.json', '.ddae/brain/manifest.json',
  'ddae-brain/x.md', 'DDAE-Brain//x.md', 'DDAE-Brain/x.MD',
];

test('B1. unsafe or out-of-policy paths are OUTPUT_PATH_INVALID and nothing at all is written (a valid sibling included)', () => {
  for (const bad of BAD_PATHS) {
    withProject(({ root }) => {
      const files = [file('Home.md'), { path: bad, content: view('x') }];
      const error = errorOf(() => writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files }));
      assert.equal(error.code, 'OUTPUT_PATH_INVALID', JSON.stringify(bad));
      assert.deepEqual(tree(root), [], `writes happened for ${JSON.stringify(bad)}`);
    });
  }
});

test('B2. the error names the offending entry by index/relative path only', () => {
  withProject(({ root }) => {
    const error = errorOf(() => writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files: [file('Home.md'), { path: '../secret.md', content: view('x') }] }));
    assert.equal(error.details.index, 1);
  });
});

const CONTROL_PATHS = ['DDAE-Brain/a\nb.md', 'DDAE-Brain/a\rb.md', 'DDAE-Brain/a\u0000b.md', 'DDAE-Brain/a\u001bb.md', 'DDAE-Brain/a\u0007b.md', 'DDAE-Brain/a\u007fb.md', 'DDAE-Brain/a\tb.md'];

test('C1. NUL, CR, LF, ESC, other ASCII controls and DEL in a basename are rejected before any write (closes the Phase A P3)', () => {
  for (const bad of CONTROL_PATHS) {
    withProject(({ root }) => {
      assert.equal(errorOf(() => writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files: [{ path: bad, content: view('x') }] })).code, 'OUTPUT_PATH_INVALID', JSON.stringify(bad));
      assert.deepEqual(tree(root), []);
    });
  }
});

test('C2. characters that are invalid in filenames on Windows (: * ? " < > |) and lone surrogates are rejected', () => {
  for (const ch of [':', '*', '?', '"', '<', '>', '|']) {
    withProject(({ root }) => {
      assert.equal(errorOf(() => writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files: [{ path: `DDAE-Brain/a${ch}b.md`, content: view('x') }] })).code, 'OUTPUT_PATH_INVALID', ch);
    });
  }
  withProject(({ root }) => {
    assert.equal(errorOf(() => writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files: [{ path: 'DDAE-Brain/a\ud800b.md', content: view('x') }] })).code, 'OUTPUT_PATH_INVALID');
  });
});

test('C3. ordinary names are accepted: spaces, hyphens, underscores, digits, accents, non-Latin scripts (no over-hardening)', () => {
  withProject(({ root }) => {
    const names = ['My View.md', 'Recent-Activity.md', 'snake_case_1.md', 'Visão-Geral.md', '日本語.md', 'ÅÄÖ.md', 'a.b.md', 'CONSOLE.md', 'COM10.md', 'LPT.md', 'NULL.md'];
    const report = writeBrainWorkspace(root, smallPlan(names));
    assert.equal(report.written.length, names.length + 1);
    for (const name of names) assert.ok(fs.existsSync(path.join(root, 'DDAE-Brain', name)), name);
  });
});

test('C4. dot-prefixed basenames are rejected (naming policy W3: generated views are visible, never hidden)', () => {
  for (const bad of ['DDAE-Brain/.hidden.md', 'DDAE-Brain/..md', 'DDAE-Brain/...md']) {
    withProject(({ root }) => {
      assert.equal(errorOf(() => writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files: [{ path: bad, content: view('x') }] })).code, 'OUTPUT_PATH_INVALID', bad);
    });
  }
});

test('C5. Windows reserved device names are rejected on every platform (portable outputs, W4)', () => {
  const reserved = ['CON', 'PRN', 'AUX', 'NUL', 'COM1', 'COM9', 'LPT1', 'LPT9', 'con', 'Nul', 'Com3'];
  for (const stem of reserved) {
    for (const name of [`${stem}.md`, `${stem}.extra.md`, `${stem} .md`]) {
      withProject(({ root }) => {
        assert.equal(errorOf(() => writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files: [{ path: `DDAE-Brain/${name}`, content: view('x') }] })).code, 'OUTPUT_PATH_INVALID', name);
        assert.deepEqual(tree(root), []);
      });
    }
  }
});

test('C6. an over-long basename (filesystem limit) is rejected before any write', () => {
  withProject(({ root }) => {
    const long = `${'a'.repeat(250)}.md`;
    assert.equal(errorOf(() => writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files: [{ path: `DDAE-Brain/${long}`, content: view('x') }] })).code, 'OUTPUT_PATH_INVALID');
    assert.deepEqual(tree(root), []);
  });
});

test('C7. content must be a string carrying the canonical ownership marker after the H1 (or the Writer could never own the file again)', () => {
  withProject(({ root }) => {
    for (const content of [42, null, '# x\n', '# x\n\nno marker here\n', `${MARKER}\n# x\n`, `# x\nno blank line\n${MARKER}\n`]) {
      const code = errorOf(() => writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files: [{ path: 'DDAE-Brain/Home.md', content }] })).code;
      assert.equal(code, typeof content === 'string' ? 'OUTPUT_CONTENT_INVALID' : 'INPUT_INVALID', JSON.stringify(content));
    }
    assert.deepEqual(tree(root), []);
  });
});

// ───────────────────────── duplicates / case ─────────────────────────

test('D1. an exact duplicate path is OUTPUT_DUPLICATE with zero writes', () => {
  withProject(({ root }) => {
    const files = [file('Home.md'), file('Sessions.md'), file('Home.md')];
    assert.equal(errorOf(() => writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files })).code, 'OUTPUT_DUPLICATE');
    assert.deepEqual(tree(root), []);
  });
});

test('D2. a case-insensitive collision is OUTPUT_CASE_COLLISION with zero writes (Windows/macOS safety)', () => {
  withProject(({ root }) => {
    const files = [file('Home.md'), file('home.md')];
    assert.equal(errorOf(() => writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files })).code, 'OUTPUT_CASE_COLLISION');
    assert.deepEqual(tree(root), []);
  });
});

// ───────────────────────── symlinks ─────────────────────────

test('S1. DDAE-Brain being a symlink/junction to elsewhere is SYMLINK_REFUSED; the outside directory is untouched', (t) => {
  withProject(({ root, outside }) => {
    if (!trySymlink(outside, path.join(root, 'DDAE-Brain'), 'junction')) return t.skip('directory symlinks not permitted on this platform');
    const error = errorOf(() => writeBrainWorkspace(root, smallPlan()));
    assert.equal(error.code, 'SYMLINK_REFUSED');
    assert.deepEqual(tree(outside), ['sentinel.txt']);
    assert.ok(!fs.existsSync(path.join(root, '.ddae')), 'no directory may be created once a symlink was found');
    return undefined;
  });
});

test('S2. .ddae being a symlink is SYMLINK_REFUSED and DDAE-Brain is not created', (t) => {
  withProject(({ root, outside }) => {
    if (!trySymlink(outside, path.join(root, '.ddae'), 'junction')) return t.skip('directory symlinks not permitted on this platform');
    assert.equal(errorOf(() => writeBrainWorkspace(root, smallPlan())).code, 'SYMLINK_REFUSED');
    assert.deepEqual(tree(outside), ['sentinel.txt']);
    assert.ok(!fs.existsSync(path.join(root, 'DDAE-Brain')));
    return undefined;
  });
});

test('S3. .ddae/brain being a symlink is SYMLINK_REFUSED (intermediate ancestor is a real directory)', (t) => {
  withProject(({ root, outside }) => {
    fs.mkdirSync(path.join(root, '.ddae'));
    if (!trySymlink(outside, path.join(root, '.ddae', 'brain'), 'junction')) return t.skip('directory symlinks not permitted on this platform');
    assert.equal(errorOf(() => writeBrainWorkspace(root, smallPlan())).code, 'SYMLINK_REFUSED');
    assert.deepEqual(tree(outside), ['sentinel.txt']);
    assert.ok(!fs.existsSync(path.join(root, 'DDAE-Brain')));
    return undefined;
  });
});

test('S4. an existing target file that is a symlink is SYMLINK_REFUSED, even with force', (t) => {
  withProject(({ root, outside }) => {
    fs.mkdirSync(path.join(root, 'DDAE-Brain'));
    const victim = path.join(outside, 'victim.md');
    fs.writeFileSync(victim, view('victim'));
    if (!trySymlink(victim, path.join(root, 'DDAE-Brain', 'Home.md'), 'file')) return t.skip('file symlinks need a privilege this platform/user does not have');
    for (const force of [false, true]) {
      assert.equal(errorOf(() => writeBrainWorkspace(root, smallPlan(), { force })).code, 'SYMLINK_REFUSED');
    }
    assert.equal(fs.readFileSync(victim, 'utf8'), view('victim'));
    return undefined;
  });
});

test('S5. a symlinked manifest target is SYMLINK_REFUSED', (t) => {
  withProject(({ root, outside }) => {
    fs.mkdirSync(path.join(root, '.ddae', 'brain'), { recursive: true });
    const victim = path.join(outside, 'victim.json');
    fs.writeFileSync(victim, '{}');
    if (!trySymlink(victim, path.join(root, '.ddae', 'brain', 'manifest.json'), 'file')) return t.skip('file symlinks need a privilege this platform/user does not have');
    assert.equal(errorOf(() => writeBrainWorkspace(root, smallPlan())).code, 'SYMLINK_REFUSED');
    assert.equal(fs.readFileSync(victim, 'utf8'), '{}');
    assert.ok(!fs.existsSync(path.join(root, 'DDAE-Brain', 'Home.md')), 'zero writes: the views were not written either');
    return undefined;
  });
});

test('S6. force never overrides symlink safety', (t) => {
  withProject(({ root, outside }) => {
    if (!trySymlink(outside, path.join(root, 'DDAE-Brain'), 'junction')) return t.skip('directory symlinks not permitted on this platform');
    assert.equal(errorOf(() => writeBrainWorkspace(root, smallPlan(), { force: true })).code, 'SYMLINK_REFUSED');
    assert.deepEqual(tree(outside), ['sentinel.txt']);
    return undefined;
  });
});

test('S7. DDAE-Brain or .ddae/brain existing as a regular file, or a target that is a directory, is TARGET_TYPE_INVALID', () => {
  withProject(({ root }) => {
    fs.writeFileSync(path.join(root, 'DDAE-Brain'), 'not a directory');
    assert.equal(errorOf(() => writeBrainWorkspace(root, smallPlan())).code, 'TARGET_TYPE_INVALID');
    assert.equal(fs.readFileSync(path.join(root, 'DDAE-Brain'), 'utf8'), 'not a directory');
  });
  withProject(({ root }) => {
    fs.mkdirSync(path.join(root, '.ddae'));
    fs.writeFileSync(path.join(root, '.ddae', 'brain'), 'not a directory');
    assert.equal(errorOf(() => writeBrainWorkspace(root, smallPlan())).code, 'TARGET_TYPE_INVALID');
    assert.ok(!fs.existsSync(path.join(root, 'DDAE-Brain')));
  });
  withProject(({ root }) => {
    fs.mkdirSync(path.join(root, 'DDAE-Brain', 'Home.md'), { recursive: true });
    assert.equal(errorOf(() => writeBrainWorkspace(root, smallPlan())).code, 'TARGET_TYPE_INVALID');
    assert.ok(!fs.existsSync(path.join(root, '.ddae')));
  });
});

// ───────────────────────── ownership / force ─────────────────────────

test('E1. an existing view carrying the marker is managed: it is overwritten', () => {
  withProject(({ root }) => {
    fs.mkdirSync(path.join(root, 'DDAE-Brain'));
    fs.writeFileSync(path.join(root, 'DDAE-Brain', 'Home.md'), view('Home', 'old body\n'));
    const report = writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files: [file('Home.md', 'new body\n')] });
    assert.ok(report.written.includes('DDAE-Brain/Home.md'));
    assert.match(read(root, 'DDAE-Brain/Home.md'), /new body/);
  });
});

test('E2. an existing unmarked file is an OWNERSHIP_CONFLICT: zero writes, the human file is intact', () => {
  withProject(({ root }) => {
    fs.mkdirSync(path.join(root, 'DDAE-Brain'));
    fs.writeFileSync(path.join(root, 'DDAE-Brain', 'Sessions.md'), '# My own notes\n');
    const error = errorOf(() => writeBrainWorkspace(root, smallPlan(['Home.md', 'Sessions.md'])));
    assert.equal(error.code, 'OWNERSHIP_CONFLICT');
    assert.equal(error.details.path, 'DDAE-Brain/Sessions.md');
    assert.equal(read(root, 'DDAE-Brain/Sessions.md'), '# My own notes\n');
    assert.deepEqual(tree(root), ['DDAE-Brain/', 'DDAE-Brain/Sessions.md'], 'Home.md and the manifest were not written');
  });
});

test('E3. the marker must be where the Renderer puts it (right after the H1, one blank line); elsewhere is not ownership', () => {
  withProject(({ root }) => {
    fs.mkdirSync(path.join(root, 'DDAE-Brain'));
    fs.writeFileSync(path.join(root, 'DDAE-Brain', 'Home.md'), `# Notes\n\nmy words\n\n${MARKER}\n`);
    assert.equal(errorOf(() => writeBrainWorkspace(root, smallPlan(['Home.md']))).code, 'OWNERSHIP_CONFLICT');
  });
});

test('E4. a generated file whose line endings were converted to CRLF is still recognised as generated', () => {
  withProject(({ root }) => {
    fs.mkdirSync(path.join(root, 'DDAE-Brain'));
    fs.writeFileSync(path.join(root, 'DDAE-Brain', 'Home.md'), view('Home', 'old\n').replace(/\n/g, '\r\n'));
    const report = writeBrainWorkspace(root, smallPlan(['Home.md']));
    assert.ok(report.written.includes('DDAE-Brain/Home.md'));
    assert.ok(!read(root, 'DDAE-Brain/Home.md').includes('\r'));
  });
});

test('F1. force: true overwrites a conflicting unmarked human file — and only that', () => {
  withProject(({ root }) => {
    fs.mkdirSync(path.join(root, 'DDAE-Brain'));
    fs.writeFileSync(path.join(root, 'DDAE-Brain', 'Sessions.md'), '# My own notes\n');
    const report = writeBrainWorkspace(root, smallPlan(['Home.md', 'Sessions.md']), { force: true });
    assert.equal(report.written.length, 3);
    assert.equal(read(root, 'DDAE-Brain/Sessions.md'), file('Sessions.md').content);
  });
});

test('F2. force never bypasses path policy, duplicates, case collisions or content policy', () => {
  for (const files of [
    [{ path: '../x.md', content: view('x') }],
    [{ path: 'DDAE-Brain/a\nb.md', content: view('x') }],
    [{ path: 'DDAE-Brain/CON.md', content: view('x') }],
    [{ path: '.ddae/brain/manifest.json', content: '{}' }],
    [file('Home.md'), file('Home.md')],
    [file('Home.md'), file('home.md')],
    [{ path: 'DDAE-Brain/Home.md', content: '# x\n' }],
  ]) {
    withProject(({ root }) => {
      errorOf(() => writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files }, { force: true }));
      assert.deepEqual(tree(root), []);
    });
  }
});

test('F3. force never bypasses an invalid project root', () => {
  withProject(({ outer }) => {
    assert.equal(errorOf(() => writeBrainWorkspace(path.join(outer, 'nope'), smallPlan(), { force: true })).code, 'PROJECT_ROOT_INVALID');
  });
});

test('F4. a corrupt existing manifest.json does not block the rebuild (machine-owned, recompilable)', () => {
  withProject(({ root }) => {
    fs.mkdirSync(path.join(root, '.ddae', 'brain'), { recursive: true });
    fs.writeFileSync(path.join(root, '.ddae', 'brain', 'manifest.json'), '{ this is not json');
    const report = writeBrainWorkspace(root, smallPlan());
    assert.ok(report.written.includes(MANIFEST_OUTPUT_PATH));
    assert.doesNotThrow(() => JSON.parse(read(root, MANIFEST_OUTPUT_PATH)));
  });
});

// ───────────────────────── idempotency ─────────────────────────

test('G1. a second identical build writes nothing: everything is reported unchanged', () => {
  withProject(({ root }) => {
    const plan = realPlan();
    writeBrainWorkspace(root, plan);
    const second = writeBrainWorkspace(root, plan);
    assert.deepEqual([...second.written], []);
    assert.equal(second.unchanged.length, plan.files.length + 1);
    assert.deepEqual([...second.unchanged], [...second.unchanged].sort());
  });
});

test('G2. identical content is not rewritten: mtimes pushed into the past survive, and no temp/rename happens', () => {
  withProject(({ root }) => {
    const plan = realPlan();
    writeBrainWorkspace(root, plan);
    const past = new Date('2001-01-01T00:00:00Z');
    const targets = [...plan.files.map((f) => f.path), MANIFEST_OUTPUT_PATH].map((rel) => path.join(root, ...rel.split('/')));
    for (const target of targets) fs.utimesSync(target, past, past);
    const calls = [];
    const restoreRename = patchFs('renameSync', (real) => (...args) => { calls.push(['rename', ...args]); return real(...args); });
    const restoreOpen = patchFs('openSync', (real) => (...args) => { if (/[wa]/.test(String(args[1] ?? 'r'))) calls.push(['open', args[0]]); return real(...args); });
    try {
      writeBrainWorkspace(root, plan);
    } finally {
      restoreRename();
      restoreOpen();
    }
    for (const target of targets) assert.equal(fs.statSync(target).mtimeMs, past.getTime(), target);
    assert.deepEqual(calls.filter(([kind]) => kind === 'rename'), []);
    assert.deepEqual(calls.filter(([kind, target]) => kind === 'open' && targets.includes(target)), []);
  });
});

test('G3. only what changed is rewritten: one changed view → that view; the manifest is rewritten only if it changed', () => {
  withProject(({ root }) => {
    writeBrainWorkspace(root, smallPlan());
    const report = writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files: [file('Home.md', 'changed\n'), file('Sessions.md')] });
    assert.deepEqual([...report.written], ['DDAE-Brain/Home.md']);
    assert.deepEqual([...report.unchanged], ['.ddae/brain/manifest.json', 'DDAE-Brain/Sessions.md']);
    const manifestOnly = writeBrainWorkspace(root, { manifest: { ...SMALL_MANIFEST, note: 'other' }, files: [file('Home.md', 'changed\n'), file('Sessions.md')] });
    assert.deepEqual([...manifestOnly.written], ['.ddae/brain/manifest.json']);
  });
});

test('G4. the report is deterministic: the same plan into two fresh projects gives deepEqual reports and identical bytes', () => {
  const plan = realPlan();
  const a = makeProject();
  const b = makeProject();
  try {
    const ra = writeBrainWorkspace(a.root, plan);
    const rb = writeBrainWorkspace(b.root, plan);
    assert.deepEqual(ra, rb);
    for (const rel of [...ra.written]) assert.equal(read(a.root, rel), read(b.root, rel));
  } finally {
    cleanup(a.outer);
    cleanup(b.outer);
  }
});

// ───────────────────────── stale_generated / unmanaged ─────────────────────────

test('H1. a generated .md that is not in the plan is reported as stale_generated and is NOT deleted', () => {
  withProject(({ root }) => {
    fs.mkdirSync(path.join(root, 'DDAE-Brain'));
    fs.writeFileSync(path.join(root, 'DDAE-Brain', 'Old-View.md'), view('Old View'));
    const report = writeBrainWorkspace(root, smallPlan());
    assert.deepEqual([...report.stale_generated], ['DDAE-Brain/Old-View.md']);
    assert.equal(read(root, 'DDAE-Brain/Old-View.md'), view('Old View'));
  });
});

test('H2. stale_generated is sorted, and only regular .md files with the marker qualify', () => {
  withProject(({ root }) => {
    const dir = path.join(root, 'DDAE-Brain');
    fs.mkdirSync(path.join(dir, 'sub'), { recursive: true });
    fs.writeFileSync(path.join(dir, 'Zeta.md'), view('Zeta'));
    fs.writeFileSync(path.join(dir, 'Alpha.md'), view('Alpha'));
    fs.writeFileSync(path.join(dir, 'notes.txt'), view('txt'));
    fs.writeFileSync(path.join(dir, 'sub', 'Nested.md'), view('Nested'));
    const report = writeBrainWorkspace(root, smallPlan());
    assert.deepEqual([...report.stale_generated], ['DDAE-Brain/Alpha.md', 'DDAE-Brain/Zeta.md']);
  });
});

test('H3. an unmarked extra file is human-owned: untouched, not stale_generated, not an error', () => {
  withProject(({ root }) => {
    fs.mkdirSync(path.join(root, 'DDAE-Brain'));
    fs.writeFileSync(path.join(root, 'DDAE-Brain', 'My-Notes.md'), '# My notes\n\nprivate\n');
    const report = writeBrainWorkspace(root, smallPlan());
    assert.deepEqual([...report.stale_generated], []);
    assert.equal(read(root, 'DDAE-Brain/My-Notes.md'), '# My notes\n\nprivate\n');
    assert.ok(!JSON.stringify(report).includes('My-Notes'));
  });
});

test('H4. planned files are never reported stale, and stale detection reads no more than the file head', () => {
  withProject(({ root }) => {
    writeBrainWorkspace(root, smallPlan());
    const report = writeBrainWorkspace(root, smallPlan());
    assert.deepEqual([...report.stale_generated], []);
  });
});

test('H5. the Writer never deletes anything: no unlink/rm/rmdir on any path except its own temp files', () => {
  withProject(({ root }) => {
    fs.mkdirSync(path.join(root, 'DDAE-Brain'));
    fs.writeFileSync(path.join(root, 'DDAE-Brain', 'Old-View.md'), view('Old'));
    const removed = [];
    const restores = ['unlinkSync', 'rmSync', 'rmdirSync'].map((name) => patchFs(name, (real) => (...args) => { removed.push(String(args[0])); return real(...args); }));
    try {
      writeBrainWorkspace(root, smallPlan());
    } finally {
      restores.forEach((restore) => restore());
    }
    assert.deepEqual(removed, [], 'a successful build has no temp file left to remove and deletes nothing else');
  });
});

// ───────────────────────── atomic write / manifest last / failure ─────────────────────────

function recordRenames(fn) {
  const renames = [];
  const opens = [];
  const restoreRename = patchFs('renameSync', (real) => (from, to) => { renames.push([from, to]); return real(from, to); });
  const restoreOpen = patchFs('openSync', (real) => (target, ...rest) => { if (/[wa]/.test(String(rest[0] ?? 'r'))) opens.push(String(target)); return real(target, ...rest); });
  try {
    fn();
  } finally {
    restoreRename();
    restoreOpen();
  }
  return { renames, opens };
}

test('I2. each file is written to a temp file in the same directory and renamed onto the target; the target is never opened directly', () => {
  withProject(({ root }) => {
    const { renames, opens } = recordRenames(() => writeBrainWorkspace(root, smallPlan()));
    assert.equal(renames.length, 3);
    for (const [from, to] of renames) {
      assert.equal(path.dirname(from), path.dirname(to));
      assert.notEqual(from, to);
      assert.ok(opens.includes(from), 'the temp file was the one opened for writing');
      assert.ok(!opens.includes(to), 'the target itself is never opened for writing');
    }
    assert.deepEqual(tree(root).filter((entry) => /tmp/i.test(entry)), [], 'no temp file remains');
  });
});

test('J1. the manifest is materialised strictly last, after every view that changed', () => {
  withProject(({ root }) => {
    const { renames } = recordRenames(() => writeBrainWorkspace(root, realPlan()));
    const order = renames.map(([, to]) => path.relative(root, to).split(path.sep).join('/'));
    assert.equal(order.at(-1), MANIFEST_OUTPUT_PATH);
    assert.deepEqual(order.slice(0, -1), [...order.slice(0, -1)].sort());
    assert.equal(new Set(order).size, order.length);
  });
});

test('K1. a failing view write throws WRITE_FAILED, never writes the manifest, keeps earlier views, and removes its temp file', () => {
  withProject(({ root }) => {
    let calls = 0;
    const restore = patchFs('renameSync', (real) => (from, to) => {
      calls += 1;
      if (calls === 2) throw Object.assign(new Error('disk on fire: SECRET_DETAIL'), { code: 'EIO' });
      return real(from, to);
    });
    let error;
    try {
      error = errorOf(() => writeBrainWorkspace(root, smallPlan(['A.md', 'B.md', 'C.md'])));
    } finally {
      restore();
    }
    assert.equal(error.code, 'WRITE_FAILED');
    assert.equal(error.details.path, 'DDAE-Brain/B.md');
    assert.deepEqual([...error.details.written], ['DDAE-Brain/A.md']);
    assert.ok(!error.message.includes('SECRET_DETAIL') && !JSON.stringify(error.details).includes('SECRET_DETAIL'));
    assert.ok(!fs.existsSync(path.join(root, '.ddae')), 'the manifest (and its directory) was not written');
    assert.deepEqual(tree(root), ['DDAE-Brain/', 'DDAE-Brain/A.md'], 'no temp file left behind, nothing after the failure written');
  });
});

test('K2. a failed rebuild leaves the previous manifest intact (it never claims the new state)', () => {
  withProject(({ root }) => {
    writeBrainWorkspace(root, smallPlan());
    const before = read(root, MANIFEST_OUTPUT_PATH);
    let calls = 0;
    const restore = patchFs('renameSync', (real) => (from, to) => {
      calls += 1;
      if (calls === 1) throw new Error('boom');
      return real(from, to);
    });
    try {
      errorOf(() => writeBrainWorkspace(root, { manifest: { ...SMALL_MANIFEST, note: 'new state' }, files: [file('Home.md', 'v2\n'), file('Sessions.md', 'v2\n')] }));
    } finally {
      restore();
    }
    assert.equal(read(root, MANIFEST_OUTPUT_PATH), before);
    assert.equal(read(root, 'DDAE-Brain/Home.md'), file('Home.md').content, 'the old target is never deleted or truncated');
  });
});

test('K3. a failing manifest write throws WRITE_FAILED, keeps the views written before it, keeps the old manifest, cleans its temp', () => {
  withProject(({ root }) => {
    writeBrainWorkspace(root, smallPlan());
    const before = read(root, MANIFEST_OUTPUT_PATH);
    const restore = patchFs('renameSync', (real) => (from, to) => {
      if (path.basename(to) === 'manifest.json') throw new Error('boom');
      return real(from, to);
    });
    let error;
    try {
      error = errorOf(() => writeBrainWorkspace(root, { manifest: { ...SMALL_MANIFEST, note: 'new' }, files: [file('Home.md', 'v2\n'), file('Sessions.md')] }));
    } finally {
      restore();
    }
    assert.equal(error.details.path, MANIFEST_OUTPUT_PATH);
    assert.deepEqual([...error.details.written], ['DDAE-Brain/Home.md']);
    assert.equal(read(root, MANIFEST_OUTPUT_PATH), before);
    assert.deepEqual(tree(path.join(root, '.ddae', 'brain')), ['manifest.json']);
  });
});

test('K4. the build is repairable: after a partial failure a new run completes and converges to the full plan', () => {
  withProject(({ root }) => {
    let calls = 0;
    const restore = patchFs('renameSync', (real) => (from, to) => {
      calls += 1;
      if (calls === 2) throw new Error('boom');
      return real(from, to);
    });
    try {
      errorOf(() => writeBrainWorkspace(root, smallPlan(['A.md', 'B.md'])));
    } finally {
      restore();
    }
    const report = writeBrainWorkspace(root, smallPlan(['A.md', 'B.md']));
    assert.deepEqual([...report.unchanged], ['DDAE-Brain/A.md']);
    assert.deepEqual([...report.written], ['.ddae/brain/manifest.json', 'DDAE-Brain/B.md']);
  });
});

test('K5. a failure to open the temp file (e.g. leftover from a crash) is WRITE_FAILED and is not silently overwritten', () => {
  withProject(({ root }) => {
    const restore = patchFs('openSync', (real) => (target, ...rest) => {
      if (String(target).includes('Home.md')) throw Object.assign(new Error('EEXIST'), { code: 'EEXIST' });
      return real(target, ...rest);
    });
    try {
      assert.equal(errorOf(() => writeBrainWorkspace(root, smallPlan())).code, 'WRITE_FAILED');
    } finally {
      restore();
    }
    assert.ok(!fs.existsSync(path.join(root, '.ddae')));
  });
});

test('K6. a failure while cleaning the temp file does not mask the original error', () => {
  withProject(({ root }) => {
    const restoreRename = patchFs('renameSync', () => () => { throw new Error('rename failed'); });
    const restoreUnlink = patchFs('unlinkSync', () => () => { throw new Error('cleanup failed'); });
    let error;
    try {
      error = errorOf(() => writeBrainWorkspace(root, smallPlan()));
    } finally {
      restoreRename();
      restoreUnlink();
    }
    assert.equal(error.code, 'WRITE_FAILED');
    assert.ok(!error.message.includes('cleanup failed'));
  });
});

// ───────────────────────── zero-write preflight ─────────────────────────

test('Z1. the preflight is complete before the first write: a conflict on the LAST file leaves the filesystem exactly as it was', () => {
  withProject(({ root }) => {
    fs.mkdirSync(path.join(root, 'DDAE-Brain'));
    fs.writeFileSync(path.join(root, 'DDAE-Brain', 'Zeta.md'), '# human\n');
    const before = tree(root);
    const restore = patchFs('renameSync', () => () => assert.fail('no rename may happen when the preflight fails'));
    try {
      assert.equal(errorOf(() => writeBrainWorkspace(root, smallPlan(['Alpha.md', 'Beta.md', 'Zeta.md']))).code, 'OWNERSHIP_CONFLICT');
    } finally {
      restore();
    }
    assert.deepEqual(tree(root), before);
  });
});

test('Z2. preflight failures create no directory at all (creating a directory is already a write)', () => {
  withProject(({ root }) => {
    assert.equal(errorOf(() => writeBrainWorkspace(root, { manifest: SMALL_MANIFEST, files: [file('Home.md'), { path: 'DDAE-Brain/x/../../y.md', content: view('x') }] })).code, 'OUTPUT_PATH_INVALID');
    assert.deepEqual(tree(root), []);
  });
});

// ───────────────────────── containment / purity ─────────────────────────

test('X1. a successful build touches nothing outside the project root', () => {
  withProject(({ outer, root, outside }) => {
    writeBrainWorkspace(root, realPlan());
    assert.deepEqual(tree(outer).filter((entry) => !entry.startsWith('project/')), ['outside/', 'outside/sentinel.txt', 'project/'].filter((entry) => entry !== 'project/'));
    assert.deepEqual(tree(outside), ['sentinel.txt']);
    assert.equal(fs.readFileSync(path.join(outside, 'sentinel.txt'), 'utf8'), 'untouched');
  });
});

test('X2. source guard: only fs/path and the canonical serializer; no Git, Docs, Context Compiler, network, clock, randomness, cwd, LLM, Claude-Mem, console', () => {
  const source = fs.readFileSync(path.join(REPO_ROOT, 'src', 'workspace', 'writer.js'), 'utf8');
  const imports = [...source.matchAll(/^import .* from '([^']+)'/gm)].map((m) => m[1]).sort();
  assert.deepEqual(imports, ['../context/fingerprint.js', 'node:fs', 'node:path']);
  const code = source.replace(/^\s*\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
  for (const forbidden of [/child_process/, /\bfetch\b/, /\bhttps?\b/, /\bnet\b/, /Date\b/, /Math\.random/, /process\.cwd/, /console\./, /claude-mem/i, /\bLLM\b/, /git-context/, /ddae-context/, /orchestrator/, /compiler/, /renderer/]) {
    assert.ok(!forbidden.test(code), String(forbidden));
  }
});

test('X3. the Writer does not need Orchestrator internals: any { manifest, files } shaped input is accepted', () => {
  withProject(({ root }) => {
    assert.doesNotThrow(() => writeBrainWorkspace(root, { manifest: { any: 'object' }, files: [file('One.md')] }));
  });
});

// Platforms/users that cannot create file symlinks (S4/S5 skip there) still exercise the same
// decision through a simulated lstat — a real file that lstat reports as a symbolic link.
function withSimulatedFileSymlink(suffix, fn) {
  const restore = patchFs('lstatSync', (real) => (target, ...rest) => {
    const stat = real(target, ...rest);
    if (String(target).endsWith(suffix)) {
      return { isSymbolicLink: () => true, isFile: () => false, isDirectory: () => false, size: stat.size };
    }
    return stat;
  });
  try {
    return fn();
  } finally {
    restore();
  }
}

test('S4b. (simulated lstat) a view target reported as a symlink is SYMLINK_REFUSED, also with force, and nothing is written', () => {
  withProject(({ root }) => {
    writeBrainWorkspace(root, smallPlan());
    const before = tree(root).map((entry) => (entry.endsWith('/') ? entry : `${entry}=${read(root, entry)}`));
    for (const force of [false, true]) {
      const error = withSimulatedFileSymlink('Home.md', () => errorOf(() => writeBrainWorkspace(root, { manifest: { ...SMALL_MANIFEST, note: 'v2' }, files: [file('Home.md', 'v2\n'), file('Sessions.md', 'v2\n')] }, { force })));
      assert.equal(error.code, 'SYMLINK_REFUSED');
      assert.equal(error.details.path, 'DDAE-Brain/Home.md');
    }
    assert.deepEqual(tree(root).map((entry) => (entry.endsWith('/') ? entry : `${entry}=${read(root, entry)}`)), before);
  });
});

test('S5b. (simulated lstat) a manifest target reported as a symlink is SYMLINK_REFUSED and no view is written either', () => {
  withProject(({ root }) => {
    writeBrainWorkspace(root, smallPlan());
    const error = withSimulatedFileSymlink('manifest.json', () => errorOf(() => writeBrainWorkspace(root, { manifest: { ...SMALL_MANIFEST, note: 'v2' }, files: [file('Home.md', 'v2\n'), file('Sessions.md')] })));
    assert.equal(error.code, 'SYMLINK_REFUSED');
    assert.equal(error.details.path, MANIFEST_OUTPUT_PATH);
    assert.equal(read(root, 'DDAE-Brain/Home.md'), file('Home.md').content, 'zero writes');
  });
});
