import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { renderBrainWorkspace, BRAIN_DIR, BRAIN_RENDERER_VIEW_PATHS } from '../src/workspace/renderer.js';
import { compileBrainManifest } from '../src/workspace/compiler.js';
import { discoverWorkspaceState } from '../src/workspace/discover.js';
import { makeSnapshot, ENGINE_VERSION } from './brain-fixtures.js';
import { REPO_ROOT, makeTempDir, cleanup } from './helpers.js';

const MARKER = '_Generated by DDAE. Derived from Docs/ and Git. Do not edit directly._';
const EXPECTED_PATHS = [
  'DDAE-Brain/Bugs.md',
  'DDAE-Brain/Decisions.md',
  'DDAE-Brain/Home.md',
  'DDAE-Brain/Recent-Activity.md',
  'DDAE-Brain/Releases.md',
  'DDAE-Brain/Risks.md',
  'DDAE-Brain/Sessions.md',
];

const compile = (overrides, options = {}) => compileBrainManifest(makeSnapshot(overrides), { engineVersion: ENGINE_VERSION, ...options });
const render = (overrides, options) => renderBrainWorkspace(compile(overrides, options));
const file = (files, name) => files.find((f) => f.path === `${BRAIN_DIR}/${name}`).content;
const clone = (value) => JSON.parse(JSON.stringify(value));

function deepFreeze(value) {
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const key of Object.keys(value)) deepFreeze(value[key]);
  }
  return value;
}

// Inline-code spans are inert data: strip them before looking for link syntax.
const stripCode = (text) => text.replace(/(`+)(.+?)\1/g, '');

function linkTargets(content) {
  return [...stripCode(content).matchAll(/\]\(([^)\s]*)\)/g)].map((m) => m[1]);
}

const EMPTY_SNAPSHOT = {
  git: { available: false, repository: false, branch: null, head: null },
  ddae: { available: false, docs_root: null, sessions_root: null, sessions: [], current_session: null },
  current_session: null,
  decisions: [],
  risks: [],
  open_bugs: [],
  recent_changes: [],
  current_tasks: [],
  release_state: { version: null, latest_tag: null },
};

// ───────────────────────── 1. determinism / purity ─────────────────────────

test('1. same manifest → same output, deepEqual and byte for byte', () => {
  const manifest = compile();
  const a = renderBrainWorkspace(manifest);
  const b = renderBrainWorkspace(manifest);
  assert.deepEqual(a, b);
  for (let i = 0; i < a.length; i += 1) {
    assert.ok(Buffer.from(a[i].content, 'utf8').equals(Buffer.from(b[i].content, 'utf8')));
    assert.equal(a[i].path, b[i].path);
  }
  assert.deepEqual(render(), a, 'rendering an independently compiled equal manifest gives the same output');
});

test('2. manifest is not mutated, including a deeply frozen one; nothing is reordered in place', () => {
  const plain = clone(compile());
  const before = JSON.stringify(plain);
  renderBrainWorkspace(plain);
  assert.equal(JSON.stringify(plain), before);
  const frozen = deepFreeze(clone(compile()));
  assert.doesNotThrow(() => renderBrainWorkspace(frozen));
});

test('3. output is a frozen array of frozen { path, content } objects with only those keys', () => {
  const files = render();
  assert.ok(Object.isFrozen(files));
  for (const entry of files) {
    assert.ok(Object.isFrozen(entry));
    assert.deepEqual(Object.keys(entry), ['path', 'content']);
    assert.equal(typeof entry.content, 'string');
  }
});

// ───────────────────────── constants / views ─────────────────────────

test('4. BRAIN_DIR is DDAE-Brain', () => {
  assert.equal(BRAIN_DIR, 'DDAE-Brain');
});

test('5. BRAIN_RENDERER_VIEW_PATHS is exactly the 7 contract views, sorted by code point, frozen, no duplicates', () => {
  assert.deepEqual([...BRAIN_RENDERER_VIEW_PATHS], EXPECTED_PATHS);
  assert.deepEqual([...BRAIN_RENDERER_VIEW_PATHS], [...BRAIN_RENDERER_VIEW_PATHS].sort());
  assert.equal(new Set(BRAIN_RENDERER_VIEW_PATHS).size, 7);
  assert.ok(Object.isFrozen(BRAIN_RENDERER_VIEW_PATHS));
});

test('6. output paths equal BRAIN_RENDERER_VIEW_PATHS exactly and are ordered by path; Home.md is present', () => {
  const paths = render().map((f) => f.path);
  assert.deepEqual(paths, [...BRAIN_RENDERER_VIEW_PATHS]);
  assert.ok(paths.includes('DDAE-Brain/Home.md'));
});

test('7. no non-contract view is produced (Context-Packages, Architecture, Current-Session, Roadmap)', () => {
  const paths = render().map((f) => f.path).join('\n');
  for (const forbidden of ['Context-Packages', 'Architecture', 'Current-Session', 'Roadmap']) {
    assert.ok(!paths.includes(forbidden), forbidden);
  }
  assert.ok(!file(render(), 'Home.md').includes('Context-Packages'));
});

// ───────────────────────── paths / root ─────────────────────────

test('8. every output path lives under DDAE-Brain/ and never under .ddae/ or any dot-folder', () => {
  for (const { path: p } of render()) {
    assert.ok(p.startsWith('DDAE-Brain/'), p);
    assert.ok(!p.startsWith('.ddae/'), p);
    assert.ok(p.split('/').every((segment) => !segment.startsWith('.')), p);
  }
});

test('9. output paths are portable: forward slashes, relative, no drive, no backslash, no ..', () => {
  for (const { path: p } of render()) {
    assert.ok(!p.includes('\\'));
    assert.ok(!p.startsWith('/'));
    assert.ok(!/^[A-Za-z]:/.test(p));
    assert.ok(!p.split('/').includes('..'));
  }
});

test('10. no output leaks an absolute machine path', () => {
  for (const { content } of render()) {
    assert.ok(!/[A-Za-z]:[\\/]/.test(content));
    assert.ok(!content.includes('\\Users'));
    assert.ok(!content.includes('/home/'));
    assert.ok(!content.includes('/Users/'));
  }
});

// ───────────────────────── marker / line endings ─────────────────────────

test('11. every file: H1, blank line, the generated marker, exactly once', () => {
  for (const { path: p, content } of render()) {
    const lines = content.split('\n');
    assert.match(lines[0], /^# \S/, p);
    assert.equal(lines[1], '', p);
    assert.equal(lines[2], MARKER, p);
    assert.equal(content.split(MARKER).length, 2, `${p} contains the marker exactly once`);
  }
});

test('12. marker is static: no timestamp, version or fingerprint on the marker line, identical across manifests', () => {
  const a = render();
  const b = render({ release_state: { version: '9.9.9', latest_tag: 'v9.9.9' } }, { engineVersion: '7.7.7' });
  for (let i = 0; i < a.length; i += 1) {
    assert.equal(a[i].content.split('\n')[2], b[i].content.split('\n')[2]);
  }
});

test('13. LF only, exactly one final newline, no BOM (byte level)', () => {
  for (const { path: p, content } of render()) {
    assert.ok(!content.includes('\r'), p);
    assert.ok(content.endsWith('\n') && !content.endsWith('\n\n'), p);
    const bytes = Buffer.from(content, 'utf8');
    assert.equal(bytes[bytes.length - 1], 0x0a);
    assert.notEqual(bytes[bytes.length - 2], 0x0a);
    assert.notEqual(bytes[0], 0xef, 'no BOM');
    assert.equal(bytes[0], 0x23, 'starts with #');
  }
});

// ───────────────────────── links ─────────────────────────

test('14. links are Markdown relative links only — no wikilinks, no absolute or file: URLs', () => {
  for (const { path: p, content } of render()) {
    assert.ok(!content.includes('[['), p);
    assert.ok(!content.includes(']]'), p);
    for (const target of linkTargets(content)) {
      assert.ok(target.startsWith('./') || target.startsWith('../'), `${p}: ${target}`);
      assert.ok(!/^[a-z]+:/i.test(target), `${p}: ${target}`);
    }
  }
});

test('15. every link points to a generated view or to a manifest source (.md), resolved from DDAE-Brain/', () => {
  const manifest = compile();
  const sourcePaths = new Set(manifest.sources.map((s) => s.path));
  let checked = 0;
  for (const { content } of renderBrainWorkspace(manifest)) {
    for (const target of linkTargets(content)) {
      checked += 1;
      if (target.startsWith('./')) {
        assert.ok(BRAIN_RENDERER_VIEW_PATHS.includes(`${BRAIN_DIR}/${target.slice(2)}`), target);
      } else {
        const decoded = decodeURIComponent(target.slice(3));
        assert.ok(sourcePaths.has(decoded), target);
        assert.ok(decoded.endsWith('.md'), target);
      }
    }
  }
  assert.ok(checked > 10);
});

test('16. Home links to the six navigable views and each view links back to Home', () => {
  const files = render();
  const home = file(files, 'Home.md');
  for (const name of ['Sessions', 'Decisions', 'Risks', 'Bugs', 'Releases', 'Recent-Activity']) {
    assert.ok(home.includes(`](./${name}.md)`), name);
    assert.ok(file(files, `${name}.md`).includes('[← Home](./Home.md)'), name);
  }
  assert.ok(!home.includes('[← Home]'));
});

test('17. link destinations are percent-encoded per segment; unsafe paths fall back to inline code without a link', () => {
  const docs = 'Docs/dir with space/(a) b#c?d é.md';
  const files = render({
    decisions: [
      { id: 'RD-01', summary: 'encoded', source_path: docs },
      { id: 'RD-02', summary: 'not linkable', source_path: 'Docs/bad\nname.md' },
      { id: 'RD-03', summary: 'not markdown', source_path: 'Docs/data.json' },
      { id: 'RD-04', summary: 'backtick in name', source_path: 'Docs/a`b.md' },
    ],
  });
  const decisions = file(files, 'Decisions.md');
  assert.ok(decisions.includes('](../Docs/dir%20with%20space/%28a%29%20b%23c%3Fd%20%C3%A9.md)'));
  const line = (id) => decisions.split('\n').find((l) => l.includes(`\`${id}\``));
  assert.ok(!line('RD-02').includes(']('), 'control char in path → no link');
  assert.ok(line('RD-02').includes('`Docs/bad name.md`'));
  assert.ok(!line('RD-03').includes(']('), 'non-.md source is code only');
  assert.ok(line('RD-03').includes('`Docs/data.json`'));
  assert.ok(line('RD-04').includes('](../Docs/a%60b.md)'));
  assert.ok(line('RD-04').includes('``a`b.md``'), 'label uses a dynamic code fence');
});

// ───────────────────────── Home ─────────────────────────

test('18. Home shows the contract sections in fixed order, from the manifest only', () => {
  const home = file(render(), 'Home.md');
  const headings = home.split('\n').filter((l) => l.startsWith('## '));
  assert.deepEqual(headings, ['## Navigation', '## Project', '## Git', '## Current Session', '## Current Tasks', '## Release State', '## Provenance']);
  assert.ok(home.startsWith('# Project Brain\n'));
  assert.ok(home.includes('`demo-project`'));
  assert.ok(home.includes('HEAD: `' + 'a'.repeat(40) + '`'));
  assert.ok(home.includes('`session_02_beta`'));
  assert.ok(home.includes('`Write tests`') && home.includes('`Write code`'));
  assert.ok(home.includes('`1.2.3`'));
});

test('19. Home provenance shows schema_version, engine_version and the manifest fingerprint', () => {
  const manifest = compile();
  const home = file(renderBrainWorkspace(manifest), 'Home.md');
  assert.ok(home.includes('`brain-manifest-v1`'));
  assert.ok(home.includes(`\`${ENGINE_VERSION}\``));
  assert.ok(home.includes(`\`${manifest.fingerprint.value}\``));
});

test('20. generated_at is never rendered and never changes the output', () => {
  const plain = render();
  const stamped = render({}, { generatedAt: '2031-05-05T05:05:05.000Z' });
  assert.deepEqual(stamped, plain);
  for (const { content } of stamped) {
    assert.ok(!content.includes('2031-05-05'));
    assert.ok(!content.toLowerCase().includes('generated_at'));
  }
});

// ───────────────────────── individual views ─────────────────────────

test('21. Sessions lists ddae sessions, marks the current one and shows its status only', () => {
  const sessions = file(render(), 'Sessions.md');
  assert.ok(sessions.includes('`session_01_alpha`'));
  const current = sessions.split('\n').find((l) => l.includes('`session_02_beta`') && l.includes('(current)'));
  assert.ok(current);
  assert.ok(sessions.includes('`Em andamento`'));
  assert.equal(sessions.split('Em andamento').length, 2, 'status appears once (only for the current session)');
  assert.ok(sessions.includes('Blocks: 2'));
  assert.ok(sessions.includes('`02_analysis`'), 'missing module is named');
  assert.ok(!sessions.includes('README'), 'does not infer a session README');
});

test('22. Decisions / Risks / Bugs use only id, source_path and summary — no invented status', () => {
  const files = render();
  const decisions = file(files, 'Decisions.md');
  const risks = file(files, 'Risks.md');
  const bugs = file(files, 'Bugs.md');
  assert.ok(decisions.includes('`RD-01`: `First decision`'));
  assert.ok(risks.includes('`MR-01`: `A risk`'));
  assert.ok(bugs.includes('`BUG-01`: `Bug in alpha`') && bugs.includes('`BUG-01`: `Bug in beta`'));
  for (const text of [decisions, risks, bugs]) {
    assert.ok(!text.includes('Aberto'), 'snapshot status must not leak (not in Manifest v1)');
    assert.ok(!/\b(status|severity|owner|priority|date)\b/i.test(text.replace(MARKER, '')), 'no invented field labels');
  }
});

test('23. Releases renders exclusively release_state', () => {
  const releases = file(render(), 'Releases.md');
  assert.ok(releases.includes('`package_version`: `1.2.3`'));
  assert.ok(releases.includes('`latest_tag`: `v1.2.3`'));
  assert.ok(releases.includes('`package.json`'));
  assert.ok(!releases.includes('](../package.json)'), 'non-markdown source is not linked');
});

test('24. Recent-Activity preserves the manifest order (no re-sort) and states the ordering honestly', () => {
  // The schema already enforces canonical (SHA) order, so the received order IS that order.
  const manifest = clone(compile({ recent_changes: ['0', '9', 'a', 'f'].map((c) => ({ sha: c.repeat(40) })) }));
  const files = renderBrainWorkspace(manifest);
  const activity = file(files, 'Recent-Activity.md');
  const rendered = [...activity.matchAll(/`([0-9a-f]{40})`/g)].map((m) => m[1]);
  assert.deepEqual(rendered, manifest.entities.recent_changes.map((c) => c.id), 'same order as received');
  assert.ok(activity.includes('Ordered by commit SHA (deterministic).'));
  assert.ok(activity.includes('not a chronological history'));
  assert.ok(!/most recent|latest first|newest/i.test(activity));
});

// ───────────────────────── empty states ─────────────────────────

test('25. empty states are explicit and deterministic for every collection', () => {
  const files = render(EMPTY_SNAPSHOT);
  assert.ok(file(files, 'Decisions.md').includes('No decisions recorded.'));
  assert.ok(file(files, 'Risks.md').includes('No risks recorded.'));
  assert.ok(file(files, 'Bugs.md').includes('No open bugs recorded.'));
  assert.ok(file(files, 'Recent-Activity.md').includes('No recent changes available (Git unavailable or no commits).'));
  assert.ok(file(files, 'Releases.md').includes('No release information available.'));
  const home = file(files, 'Home.md');
  assert.ok(home.includes("No open tasks in the current session's latest block."));
  assert.ok(home.includes('No release information available.'));
  assert.deepEqual(render(EMPTY_SNAPSHOT), files);
});

test('26. Git unavailable → "Git: not available." and "HEAD: n/a"; no other Git source is consulted', () => {
  const home = file(render(EMPTY_SNAPSHOT), 'Home.md');
  assert.ok(home.includes('Git: not available.'));
  assert.ok(home.includes('HEAD: n/a'));
  const noCommits = file(render({ git: { available: true, repository: true, branch: 'main', head: null } }), 'Home.md');
  assert.ok(noCommits.includes('Git: available.'));
  assert.ok(noCommits.includes('HEAD: n/a'));
});

test('27. DDAE control plane missing and current session absent are distinct empty states', () => {
  const missing = render(EMPTY_SNAPSHOT);
  assert.ok(file(missing, 'Home.md').includes('DDAE control plane (Docs/) not found.'));
  assert.ok(file(missing, 'Sessions.md').includes('DDAE control plane (Docs/) not found.'));
  const noSession = render({
    ddae: { available: true, docs_root: 'Docs', sessions_root: 'Docs/05_sessions', sessions: [], current_session: null },
    current_session: null,
  });
  assert.ok(file(noSession, 'Home.md').includes('No canonical session found.'));
  assert.ok(file(noSession, 'Sessions.md').includes('No canonical session found.'));
  assert.ok(file(noSession, 'Sessions.md').includes('No sessions found.'));
  assert.ok(!file(noSession, 'Home.md').includes('control plane'));
});

test('28. a manifest with no entities at all renders 7 valid, non-empty documents', () => {
  const files = render(EMPTY_SNAPSHOT);
  assert.equal(files.length, 7);
  for (const { content } of files) assert.ok(content.length > 50);
});

// ───────────────────────── markdown safety ─────────────────────────

test('29. adversarial summaries stay inert: one line, dynamic fence, no structure injected', () => {
  const nasty = 'Use `code` and ``double`` | pipe [x](y) [[wiki]] <b>html</b> ---\n# heading\tTab sep\u0007bell ![img](x)';
  const normalized = 'Use `code` and ``double`` | pipe [x](y) [[wiki]] <b>html</b> --- # heading Tab sep bell ![img](x)';
  const files = render({ decisions: [{ id: 'RD-01', summary: nasty, source_path: 'Docs/04_governance/registro_decisoes.md' }] });
  const decisions = file(files, 'Decisions.md');
  const lines = decisions.split('\n');
  const entryLines = lines.filter((l) => l.includes('RD-01'));
  assert.equal(entryLines.length, 1, 'multiline summary collapses to a single line');
  assert.ok(entryLines[0].includes(`\`\`\`${normalized}\`\`\``), 'fence is longer than the longest backtick run in the content');
  const headings = lines.filter((l) => l.startsWith('#'));
  assert.deepEqual(headings, ['# Decisions', '## Index']);
  assert.ok(!/[\u0000-\u0008\u000b-\u001f\u007f\u2028\u2029]/.test(decisions));
  assert.equal(decisions.split('\n---').length, 1, 'no frontmatter/hr delimiter line is created');
});

test('30. ids, project name and paths containing backticks/wikilinks/HTML are rendered as inert inline code', () => {
  const files = render({
    project: { name: 'my `proj` [[x]] <i>', root_relative_path: '.' },
    risks: [{ id: 'R`1', summary: '   ', status: 'x', source_path: 'Docs/04_governance/matriz_riscos.md' }],
  });
  const home = file(files, 'Home.md');
  assert.ok(home.includes('Name: ``my `proj` [[x]] <i>``'));
  const risks = file(files, 'Risks.md');
  assert.ok(risks.includes('``R`1``'));
  assert.ok(!home.split('\n').some((l) => /^\s*\[\[/.test(l)));
});

test('31. long summaries are never truncated and special Unicode is preserved', () => {
  const long = `${'ação — ünïcödé 日本語 🙂 '.repeat(200)}end`;
  const decisions = file(render({ decisions: [{ id: 'RD-09', summary: long, source_path: 'Docs/x.md' }] }), 'Decisions.md');
  assert.ok(decisions.includes(long));
});

test('32. an empty summary is rendered as a valid code span, never dropped', () => {
  const decisions = file(render({ decisions: [{ id: 'RD-05', summary: '', source_path: 'Docs/x.md' }] }), 'Decisions.md');
  assert.ok(decisions.split('\n').some((l) => l.includes('`RD-05`')));
});

// ───────────────────────── manifest.views (transitional) ─────────────────────────

test('33. manifest.views is never mutated, synchronized or consulted', () => {
  const emptyViews = clone(compile());
  assert.deepEqual(emptyViews.views, []);
  const filled = clone(emptyViews);
  filled.views = ['DDAE-Brain/Home.md'];
  const before = JSON.stringify(filled);
  const out1 = renderBrainWorkspace(emptyViews);
  const out2 = renderBrainWorkspace(filled);
  assert.equal(JSON.stringify(filled), before);
  assert.deepEqual(emptyViews.views, []);
  assert.deepEqual(out1, out2, 'output does not depend on manifest.views');
});

test('34. TRANSITIONAL: the current Compiler emits views [] while the Renderer declares 7 paths — no runtime equality is required yet (closed in Bloco 08)', () => {
  const manifest = compile();
  assert.deepEqual([...manifest.views], []);
  assert.equal(renderBrainWorkspace(manifest).length, BRAIN_RENDERER_VIEW_PATHS.length);
});

// ───────────────────────── validation ─────────────────────────

test('35. an invalid manifest is rejected (via the existing schema), never "fixed"', () => {
  assert.throws(() => renderBrainWorkspace(null), /Brain Manifest/);
  assert.throws(() => renderBrainWorkspace({}), /Brain Manifest/);
  const broken = clone(compile());
  broken.schema_version = 'brain-manifest-v9';
  assert.throws(() => renderBrainWorkspace(broken), /schema_version/);
  const extra = clone(compile());
  extra.memory = [];
  assert.throws(() => renderBrainWorkspace(extra), /memory/);
});

// ───────────────────────── source guard ─────────────────────────

const readCode = (...segments) => fs.readFileSync(path.join(REPO_ROOT, ...segments), 'utf8')
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .replace(/^\s*\/\/.*$/gm, '');

test('36. the renderer is pure: no fs/network/clock/randomness/cwd/collectors/Claude-Mem/memory provider', () => {
  const code = readCode('src', 'workspace', 'renderer.js');
  for (const token of [
    'node:fs', 'fs/promises', 'node:child_process', 'node:http', 'node:https', 'node:net', 'fetch(',
    'Date.now', 'new Date', 'Math.random', 'randomUUID', 'process.cwd', 'process.env',
    'collectDdaeContext', 'collectGitContext', 'discoverWorkspaceState', 'compileBrainManifest',
    'writeFile', 'mkdirSync', 'wikilink',
  ]) {
    assert.ok(!code.includes(token), `renderer.js must not reference ${token}`);
  }
  const lower = code.toLowerCase();
  assert.ok(!lower.includes('claude-mem') && !lower.includes('memoryprovider'));
  const imports = [...code.matchAll(/from\s+'([^']+)'/g)].map((m) => m[1]);
  assert.deepEqual(imports.sort(), ['../schemas/brain-schema.js']);
});

// ───────────────────────── integration ─────────────────────────

function write(root, rel, content) {
  const abs = path.join(root, rel);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content, 'utf8');
}

function assertRealLinks(files, root) {
  let checked = 0;
  for (const { content } of files) {
    for (const target of linkTargets(content)) {
      if (target.startsWith('../')) {
        checked += 1;
        assert.ok(fs.existsSync(path.join(root, decodeURIComponent(target.slice(3)))), `dangling link ${target}`);
      }
    }
  }
  return checked;
}

test('37. integration: Discovery → Compiler → Renderer on a temp project — 7 views, real links, zero writes', () => {
  const dir = makeTempDir();
  try {
    write(dir, 'package.json', JSON.stringify({ name: 'demo', version: '3.1.4' }));
    write(dir, 'Docs/05_sessions/session_01_demo/README.md', '# Session\n\n## 5. Status\n\n- [ ] Não iniciada\n- [x] Em andamento\n');
    write(dir, 'Docs/05_sessions/session_01_demo/05_blocks/bloco_01_x.md', '# Bloco 01 — X\n\n- [ ] Do the `first` | thing\n');
    write(dir, 'Docs/04_governance/registro_decisoes.md', '# Registro\n\n### RD-01 — Pick `pipes | and` [[links]]\n\n- **Status:** Vigente\n');
    write(dir, 'Docs/04_governance/matriz_riscos.md', '# M\n\n| ID | Risco | Área | Probabilidade | Impacto | Status |\n|---|---|---|---|---|---|\n| MR-01 | Something `risky` | x | a | b | Aberto |\n');
    const list = () => fs.readdirSync(dir, { recursive: true }).sort();
    const before = list();
    const manifest = compileBrainManifest(discoverWorkspaceState(dir), { engineVersion: ENGINE_VERSION });
    const manifestJson = JSON.stringify(manifest);
    const files = renderBrainWorkspace(manifest);
    const again = renderBrainWorkspace(compileBrainManifest(discoverWorkspaceState(dir), { engineVersion: ENGINE_VERSION }));
    assert.deepEqual(files.map((f) => f.path), [...BRAIN_RENDERER_VIEW_PATHS]);
    assert.deepEqual(files, again);
    assert.equal(JSON.stringify(manifest), manifestJson, 'manifest not mutated');
    assert.deepEqual([...manifest.views], [], 'transitional: compiler still emits views []');
    assert.ok(file(files, 'Decisions.md').includes('``Pick `pipes | and` [[links]]``'));
    assert.ok(file(files, 'Risks.md').includes('`` Something `risky` ``'), 'content ending in a backtick gets a padded fence');
    assert.ok(file(files, 'Home.md').includes('``Do the `first` | thing``'));
    assert.ok(assertRealLinks(files, dir) >= 3);
    assert.deepEqual(list(), before, 'no filesystem write');
    assert.ok(!fs.existsSync(path.join(dir, 'DDAE-Brain')));
    assert.ok(!fs.existsSync(path.join(dir, '.ddae')));
  } finally {
    cleanup(dir);
  }
});

test('38. integration: the DDAE self-host renders 7 views with only real links and writes nothing', () => {
  const engineVersion = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'package.json'), 'utf8')).version;
  const brainDir = path.join(REPO_ROOT, 'DDAE-Brain');
  const machineDir = path.join(REPO_ROOT, '.ddae', 'brain');
  assert.ok(!fs.existsSync(brainDir) && !fs.existsSync(machineDir));
  const manifest = compileBrainManifest(discoverWorkspaceState(REPO_ROOT), { engineVersion });
  const files = renderBrainWorkspace(manifest);
  assert.deepEqual(files.map((f) => f.path), [...BRAIN_RENDERER_VIEW_PATHS]);
  assert.deepEqual(files, renderBrainWorkspace(manifest));
  assert.ok(assertRealLinks(files, REPO_ROOT) >= 1);
  for (const { content } of files) {
    assert.ok(!content.includes('[['));
    assert.ok(!/[A-Za-z]:[\\/]/.test(content));
  }
  assert.ok(!fs.existsSync(brainDir) && !fs.existsSync(machineDir), 'nothing written by rendering');
});
