import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createSource } from '../src/context/authority.js';
import { compileContext } from '../src/context/compiler.js';
import { stableStringify } from '../src/context/fingerprint.js';
import {
  collectContextPackageState,
  renderContextPackagesView,
  CONTEXT_PACKAGES_VIEW_PATH,
} from '../src/workspace/context-packages.js';
import { BRAIN_DIR } from '../src/workspace/renderer.js';
import { REPO_ROOT, makeTempDir, cleanup } from './helpers.js';

const MARKER = '_Generated by DDAE. Derived from Docs/ and Git. Do not edit directly._';
const SECRET_CONTENT = 'SUPER_SECRET_CONTENT_123';
const SECRET_GOAL_TEXT = 'PRIVATE_GOAL_TEXT_456';
const SECRET_GOAL_NORMALIZED = 'normalized_private_goal_789';

function gitFixture(overrides = {}) {
  return {
    available: true,
    repository: true,
    branch: 'main',
    head: 'a'.repeat(40),
    working_tree: 'clean',
    modified_files: [],
    untracked_files: [],
    recent_commits: [],
    tags: [],
    warnings: [],
    ...overrides,
  };
}

function ddaeFixture(overrides = {}) {
  return {
    available: true,
    current_session: { name: 'session_06_x', path: 'Docs/05_sessions/session_06_x' },
    selection: { requested: null, selected: 'session_06_x', reason: 'latest_canonical' },
    ...overrides,
  };
}

function candidateWithContent(idSeed, content, extra = {}) {
  const source = createSource({ kind: 'documentation', domain: 'history', identity: idSeed, content, ...extra });
  return { source, content, signals: extra.signals };
}

/** A real, schema-valid Context Manifest v1 — built with the actual compiler, never hand-typed. */
function buildManifest(overrides = {}) {
  return compileContext({
    engineVersion: '0.3.0',
    project: { name: 'demo', root_kind: 'ddae' },
    goal: SECRET_GOAL_TEXT,
    gitContext: gitFixture(),
    ddaeContext: ddaeFixture(),
    candidates: [candidateWithContent('doc_a', SECRET_CONTENT, { path: 'Docs/a.md' })],
    ...overrides,
  });
}

function write(root, rel, content) {
  const abs = path.join(root, rel);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content, 'utf8');
}

function contextDir(root) {
  return path.join(root, '.ddae', 'context');
}

function writeManifest(root, manifest) {
  write(root, '.ddae/context/manifest.json', `${stableStringify(manifest)}\n`);
}

function writeValidation(root, receipt) {
  write(root, '.ddae/context/validation.json', `${stableStringify(receipt)}\n`);
}

function buildValidationReceipt(manifest, status = 'VALID', reasons = []) {
  return { schema_version: manifest.schema_version, status, fingerprint: manifest.fingerprint.value, reasons };
}

// ───────────────────────── module / API / path ─────────────────────────

test('1. exports the expected API', () => {
  assert.equal(typeof collectContextPackageState, 'function');
  assert.equal(typeof renderContextPackagesView, 'function');
  assert.equal(CONTEXT_PACKAGES_VIEW_PATH, `${BRAIN_DIR}/Context-Packages.md`);
  assert.equal(CONTEXT_PACKAGES_VIEW_PATH, 'DDAE-Brain/Context-Packages.md');
});

// ───────────────────────── states: missing ─────────────────────────

test('2. missing: no .ddae/context/ at all → a valid, explicit "missing" state, no exception', () => {
  const dir = makeTempDir();
  try {
    const state = collectContextPackageState(dir);
    assert.deepEqual(state, { availability: 'missing', status: null, reasons: [], schema_version: null, engine_version: null, goal_hash: null, budget: null, fingerprint: null, counts: null, relevant_files: [] });
    assert.ok(Object.isFrozen(state));
  } finally {
    cleanup(dir);
  }
});

test('3. missing view renders a valid, explicit empty state document', () => {
  const dir = makeTempDir();
  try {
    const content = file(renderContextPackagesView(collectContextPackageState(dir)));
    assert.match(content, /^# Context Packages\n\n_Generated by DDAE\. Derived from Docs\/ and Git\. Do not edit directly\.\_\n\n/);
    assert.ok(/no context package/i.test(content));
    assert.ok(content.includes('[Home](./Home.md)'));
  } finally {
    cleanup(dir);
  }
});

function file(entry) {
  assert.equal(entry.path, CONTEXT_PACKAGES_VIEW_PATH);
  return entry.content;
}

// ───────────────────────── states: valid / stale / invalid ─────────────────────────

test('4. valid: a package with no relevant_files (nothing left unverified) → VALID', () => {
  const dir = makeTempDir();
  try {
    // With relevant_files present, source freshness is deliberately never
    // reverified (D2/Seção 12.3) and the result is always STALE — see test 5.
    // A true VALID is only reachable when there is nothing left to verify.
    const degraded = buildManifest({ gitContext: { available: false }, ddaeContext: { available: false }, candidates: [] });
    writeManifest(dir, degraded);
    writeValidation(dir, buildValidationReceipt(degraded));
    const state = collectContextPackageState(dir);
    assert.equal(state.availability, 'present');
    assert.equal(state.status, 'VALID');
    assert.deepEqual(state.reasons, []);
    assert.equal(state.schema_version, degraded.schema_version);
    assert.equal(state.engine_version, '0.3.0');
    assert.equal(state.budget.profile, degraded.budget.profile);
    assert.equal(state.fingerprint.value, degraded.fingerprint.value);
    assert.deepEqual(state.counts, { sources: degraded.sources.length, relevant_files: degraded.relevant_files.length, excluded_sources: degraded.excluded_sources.length });
  } finally {
    cleanup(dir);
  }
});

test('5. stale: git HEAD in the manifest no longer matches the real repository → STALE, GIT_HEAD_CHANGED', () => {
  const dir = makeTempDir();
  try {
    fs.mkdirSync(path.join(dir, '.git')); // presence alone is not enough to make collectGitContext see a real repo; this test instead forces staleness via relevant_files with no hash verification, which is always achievable without a real git repo:
    const manifest = buildManifest({ gitContext: { available: false }, ddaeContext: { available: false } });
    writeManifest(dir, manifest);
    writeValidation(dir, buildValidationReceipt(manifest));
    const state = collectContextPackageState(dir);
    assert.equal(state.status, 'STALE');
    assert.ok(state.reasons.some((r) => r.code === 'SOURCE_FRESHNESS_UNVERIFIED'));
  } finally {
    cleanup(dir);
  }
});

test('6. schema_version mismatch (or any Context Schema violation) → CORRUPT, MANIFEST_SCHEMA_INVALID, no leaked detail beyond the code', () => {
  // The collector runs the Context Schema check up front, before ever calling
  // validateContextState — a deliberate, more conservative choice than reusing
  // validateContextState's own MANIFEST_INVALID reason, whose `errors` array
  // can otherwise carry arbitrary field values (e.g. `got ${JSON.stringify(...)}`)
  // assembled from the malformed manifest. A single generic, content-free code
  // covers every way a manifest can fail the schema (Seção 12.3 of the block).
  const dir = makeTempDir();
  try {
    const manifest = buildManifest({ gitContext: { available: false }, ddaeContext: { available: false }, candidates: [] });
    const tampered = { ...manifest, schema_version: '999' };
    writeManifest(dir, tampered);
    const state = collectContextPackageState(dir);
    assert.equal(state.status, 'CORRUPT');
    assert.deepEqual(state.reasons, [{ code: 'MANIFEST_SCHEMA_INVALID' }]);
    assert.ok(!JSON.stringify(state).includes('999'), 'the tampered value itself is never echoed back');
  } finally {
    cleanup(dir);
  }
});

test('7. corrupt manifest.json (not valid JSON) → CORRUPT, no exception, no schema fields', () => {
  const dir = makeTempDir();
  try {
    write(dir, '.ddae/context/manifest.json', '{ not json');
    const state = collectContextPackageState(dir);
    assert.equal(state.availability, 'present');
    assert.equal(state.status, 'CORRUPT');
    assert.deepEqual(state.reasons, [{ code: 'MANIFEST_JSON_INVALID' }]);
    assert.equal(state.schema_version, null);
    assert.equal(state.fingerprint, null);
  } finally {
    cleanup(dir);
  }
});

test('8. corrupt validation.json (not valid JSON) never blocks a valid manifest from being classified', () => {
  const dir = makeTempDir();
  try {
    const manifest = buildManifest({ gitContext: { available: false }, ddaeContext: { available: false } });
    writeManifest(dir, manifest);
    write(dir, '.ddae/context/validation.json', '{ not json');
    const state = collectContextPackageState(dir);
    assert.equal(state.availability, 'present');
    assert.notEqual(state.status, 'CORRUPT');
  } finally {
    cleanup(dir);
  }
});

test('9. partial: .ddae/context/ exists with other files but no manifest.json → treated as "missing" (no usable package)', () => {
  const dir = makeTempDir();
  try {
    write(dir, '.ddae/context/validation.json', '{}');
    const state = collectContextPackageState(dir);
    assert.equal(state.availability, 'missing');
  } finally {
    cleanup(dir);
  }
});

test('10. manifest.json valid JSON but fails the Context Manifest schema → CORRUPT, distinct from a well-formed-but-stale manifest', () => {
  const dir = makeTempDir();
  try {
    write(dir, '.ddae/context/manifest.json', '{"schema_version":"1"}');
    const state = collectContextPackageState(dir);
    assert.equal(state.status, 'CORRUPT');
    assert.deepEqual(state.reasons, [{ code: 'MANIFEST_SCHEMA_INVALID' }]);
  } finally {
    cleanup(dir);
  }
});

// ───────────────────────── relevant_files metadata ─────────────────────────

test('11. relevant_files metadata: path, score, char_cost only — in manifest order, never content', () => {
  const dir = makeTempDir();
  try {
    const manifest = buildManifest({
      gitContext: { available: false },
      ddaeContext: { available: false },
      candidates: [
        candidateWithContent('doc_a', SECRET_CONTENT, { path: 'Docs/a.md' }),
        candidateWithContent('doc_b', 'second file content', { path: 'Docs/b.md' }),
      ],
      goal: 'a b',
    });
    writeManifest(dir, manifest);
    const state = collectContextPackageState(dir);
    assert.ok(state.relevant_files.length >= 1);
    for (const entry of state.relevant_files) {
      assert.deepEqual(Object.keys(entry).sort(), ['char_cost', 'path', 'score']);
    }
    assert.deepEqual(state.relevant_files.map((f) => f.path), manifest.relevant_files.map((f) => f.path));
  } finally {
    cleanup(dir);
  }
});

// ───────────────────────── sensitive data ─────────────────────────

test('12/13. sensitive sentinels (file content, goal.text, goal.normalized) never reach the safe state', () => {
  const dir = makeTempDir();
  try {
    const manifest = buildManifest({ gitContext: { available: false }, ddaeContext: { available: false } });
    assert.ok(manifest.relevant_files.some((f) => f.content.includes(SECRET_CONTENT)), 'sanity: the manifest really carries the secret');
    assert.equal(manifest.goal.text, SECRET_GOAL_TEXT);
    writeManifest(dir, manifest);
    const state = collectContextPackageState(dir);
    const serialized = JSON.stringify(state);
    assert.ok(!serialized.includes(SECRET_CONTENT));
    assert.ok(!serialized.includes(SECRET_GOAL_TEXT));
    assert.ok(!serialized.includes(manifest.goal.normalized));
    assert.ok(!('goal' in state), 'no raw goal object is carried at all');
    assert.equal(state.goal_hash, manifest.goal.hash);
  } finally {
    cleanup(dir);
  }
});

test('14. sensitive sentinels never reach the rendered view either', () => {
  const dir = makeTempDir();
  try {
    const manifest = buildManifest({ gitContext: { available: false }, ddaeContext: { available: false } });
    writeManifest(dir, manifest);
    const content = file(renderContextPackagesView(collectContextPackageState(dir)));
    assert.ok(!content.includes(SECRET_CONTENT));
    assert.ok(!content.includes(SECRET_GOAL_TEXT));
    assert.ok(!content.includes(manifest.goal.normalized));
    assert.ok(!content.toLowerCase().includes('context.md'));
  } finally {
    cleanup(dir);
  }
});

test('15. CONTEXT.md content on disk is never read even when present next to manifest.json', () => {
  const dir = makeTempDir();
  try {
    const manifest = buildManifest({ gitContext: { available: false }, ddaeContext: { available: false } });
    writeManifest(dir, manifest);
    write(dir, '.ddae/context/CONTEXT.md', `leaked content ${SECRET_CONTENT}`);
    const state = collectContextPackageState(dir);
    const content = file(renderContextPackagesView(state));
    assert.ok(!JSON.stringify(state).includes(SECRET_CONTENT));
    assert.ok(!content.includes(SECRET_CONTENT));
  } finally {
    cleanup(dir);
  }
});

// ───────────────────────── path safety ─────────────────────────

test('16. no absolute machine path, backslash or Windows drive appears in state or view', () => {
  const dir = makeTempDir();
  try {
    const manifest = buildManifest({ gitContext: { available: false }, ddaeContext: { available: false } });
    writeManifest(dir, manifest);
    const state = collectContextPackageState(dir);
    const content = file(renderContextPackagesView(state));
    for (const text of [JSON.stringify(state), content]) {
      assert.ok(!/[A-Za-z]:[\\/]/.test(text));
      assert.ok(!text.includes(dir.split(path.sep).join('/')));
    }
  } finally {
    cleanup(dir);
  }
});

test('17. no link is ever generated to .ddae/context/ (manifest.json, validation.json or CONTEXT.md)', () => {
  const dir = makeTempDir();
  try {
    const manifest = buildManifest({ gitContext: { available: false }, ddaeContext: { available: false } });
    writeManifest(dir, manifest);
    const content = file(renderContextPackagesView(collectContextPackageState(dir)));
    assert.ok(!content.includes('](../.ddae'));
    assert.ok(!content.includes('.ddae/context'));
    assert.ok(!content.match(/\]\([^)]*\.ddae/));
  } finally {
    cleanup(dir);
  }
});

// ───────────────────────── determinism / purity / immutability ─────────────────────────

test('18. same state → same output byte for byte', () => {
  const dir = makeTempDir();
  try {
    const manifest = buildManifest({ gitContext: { available: false }, ddaeContext: { available: false } });
    writeManifest(dir, manifest);
    const state = collectContextPackageState(dir);
    const a = renderContextPackagesView(state);
    const b = renderContextPackagesView(state);
    assert.deepEqual(a, b);
    assert.ok(Buffer.from(a.content, 'utf8').equals(Buffer.from(b.content, 'utf8')));
  } finally {
    cleanup(dir);
  }
});

test('19. accepts a deeply frozen state and does not mutate it', () => {
  const dir = makeTempDir();
  try {
    const state = collectContextPackageState(dir); // missing state, already frozen
    const before = JSON.stringify(state);
    deepFreeze(state);
    renderContextPackagesView(state);
    assert.equal(JSON.stringify(state), before);
  } finally {
    cleanup(dir);
  }
});

function deepFreeze(value) {
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const key of Object.keys(value)) deepFreeze(value[key]);
  }
  return value;
}

test('20. generated marker, LF, exactly one trailing newline, no frontmatter', () => {
  const dir = makeTempDir();
  try {
    for (const state of [collectContextPackageState(dir)]) {
      const content = file(renderContextPackagesView(state));
      const lines = content.split('\n');
      assert.equal(lines[0], '# Context Packages');
      assert.equal(lines[1], '');
      assert.equal(lines[2], MARKER);
      assert.ok(!content.includes('\r'));
      assert.ok(content.endsWith('\n') && !content.endsWith('\n\n'));
      assert.ok(!content.split('\n').some((l) => l === '---'));
    }
  } finally {
    cleanup(dir);
  }
});

test('21. Home backlink present; no forward link from Home is asserted here (D3, deferred to Bloco 08)', () => {
  const dir = makeTempDir();
  const content = file(renderContextPackagesView(collectContextPackageState(dir)));
  cleanup(dir);
  assert.ok(content.includes('[Home](./Home.md)'));
});

const readCode = (...segments) => fs.readFileSync(path.join(REPO_ROOT, ...segments), 'utf8')
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .replace(/^\s*\/\/.*$/gm, '');

test('22. renderContextPackagesView is pure: no fs/network/clock/randomness/Git/Docs/Claude-Mem, imports only the schema-free minimum', () => {
  const code = readCode('src', 'workspace', 'context-packages.js');
  for (const token of ['fetch(', 'node:http', 'node:https', 'node:net', 'node:child_process', 'Date.now', 'new Date', 'Math.random', 'randomUUID', 'collectGitContext', 'collectDdaeContext', 'compileContext', 'renderContextMarkdown']) {
    assert.ok(!code.includes(token), `context-packages.js must not reference ${token}`);
  }
  const lower = code.toLowerCase();
  assert.ok(!lower.includes('claude-mem') && !lower.includes('memoryprovider'));
});

test('23. the collector is the only I/O boundary: no filesystem write ever happens, in any state', () => {
  const dir = makeTempDir();
  try {
    write(dir, 'package.json', '{}');
    const list = () => fs.readdirSync(dir, { recursive: true }).sort();
    const before = list();
    const manifest = buildManifest({ gitContext: { available: false }, ddaeContext: { available: false } });
    writeManifest(dir, manifest);
    writeValidation(dir, buildValidationReceipt(manifest));
    const listAfterWrite = list();
    const state = collectContextPackageState(dir);
    renderContextPackagesView(state);
    assert.deepEqual(list(), listAfterWrite);
    assert.ok(!fs.existsSync(path.join(dir, 'DDAE-Brain')));
  } finally {
    cleanup(dir);
  }
});

test('24. non-object / garbage input to the collector never throws — projectRoot must still be a real directory', () => {
  assert.throws(() => collectContextPackageState(path.join(makeTempDir(), 'nope-does-not-exist')), /does not exist|not a directory/);
});

// ───────────────────────── self-host ─────────────────────────

test('25. self-host: works against the real repository whether or not .ddae/context/ currently exists locally', () => {
  const hasContext = fs.existsSync(path.join(REPO_ROOT, '.ddae', 'context', 'manifest.json'));
  const state = collectContextPackageState(REPO_ROOT);
  assert.equal(state.availability, hasContext ? 'present' : 'missing');
  const content = file(renderContextPackagesView(state));
  assert.ok(content.startsWith('# Context Packages'));
  assert.ok(!/[A-Za-z]:[\\/]/.test(content));
  assert.ok(!content.includes(REPO_ROOT.split(path.sep).join('/')));
});
