import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { renderBrainWorkspace, BRAIN_DIR, BRAIN_RENDERER_VIEW_PATHS } from '../src/workspace/renderer.js';
import { compileBrainManifest } from '../src/workspace/compiler.js';
import { discoverWorkspaceState } from '../src/workspace/discover.js';
import { makeSnapshot, ENGINE_VERSION } from './brain-fixtures.js';
import { REPO_ROOT, makeTempDir, cleanup } from './helpers.js';

const MARKER = '_Generated by DDAE. Derived from Docs/ and Git. Do not edit directly._';
const EXPECTED_PATHS = [
  'DDAE-Brain/Bugs.md',
  'DDAE-Brain/Decisions.md',
  'DDAE-Brain/Home.md',
  'DDAE-Brain/Recent-Activity.md',
  'DDAE-Brain/Releases.md',
  'DDAE-Brain/Risks.md',
  'DDAE-Brain/Sessions.md',
];

const compile = (overrides, options = {}) => compileBrainManifest(makeSnapshot(overrides), { engineVersion: ENGINE_VERSION, ...options });
const render = (overrides, options) => renderBrainWorkspace(compile(overrides, options));
const file = (files, name) => files.find((f) => f.path === `${BRAIN_DIR}/${name}`).content;
const clone = (value) => JSON.parse(JSON.stringify(value));

function deepFreeze(value) {
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const key of Object.keys(value)) deepFreeze(value[key]);
  }
  return value;
}

// Inline-code spans are inert data: strip them before looking for link syntax.
const stripCode = (text) => text.replace(/(`+)(.+?)\1/g, '');

function linkTargets(content) {
  return [...stripCode(content).matchAll(/\]\(([^)\s]*)\)/g)].map((m) => m[1]);
}

const EMPTY_SNAPSHOT = {
  git: { available: false, repository: false, branch: null, head: null },
  ddae: { available: false, docs_root: null, sessions_root: null, sessions: [], current_session: null },
  current_session: null,
  decisions: [],
  risks: [],
  open_bugs: [],
  recent_changes: [],
  current_tasks: [],
  release_state: { version: null, latest_tag: null },
};

// ───────────────────────── 1. determinism / purity ─────────────────────────

test('1. same manifest → same output, deepEqual and byte for byte', () => {
  const manifest = compile();
  const a = renderBrainWorkspace(manifest);
  const b = renderBrainWorkspace(manifest);
  assert.deepEqual(a, b);
  for (let i = 0; i < a.length; i += 1) {
    assert.ok(Buffer.from(a[i].content, 'utf8').equals(Buffer.from(b[i].content, 'utf8')));
    assert.equal(a[i].path, b[i].path);
  }
  assert.deepEqual(render(), a, 'rendering an independently compiled equal manifest gives the same output');
});

test('2. manifest is not mutated, including a deeply frozen one; nothing is reordered in place', () => {
  const plain = clone(compile());
  const before = JSON.stringify(plain);
  renderBrainWorkspace(plain);
  assert.equal(JSON.stringify(plain), before);
  const frozen = deepFreeze(clone(compile()));
  assert.doesNotThrow(() => renderBrainWorkspace(frozen));
});

test('3. output is a frozen array of frozen { path, content } objects with only those keys', () => {
  const files = render();
  assert.ok(Object.isFrozen(files));
  for (const entry of files) {
    assert.ok(Object.isFrozen(entry));
    assert.deepEqual(Object.keys(entry), ['path', 'content']);
    assert.equal(typeof entry.content, 'string');
  }
});

// ───────────────────────── constants / views ─────────────────────────

test('4. BRAIN_DIR is DDAE-Brain', () => {
  assert.equal(BRAIN_DIR, 'DDAE-Brain');
});

test('5. BRAIN_RENDERER_VIEW_PATHS is exactly the 7 contract views, sorted by code point, frozen, no duplicates', () => {
  assert.deepEqual([...BRAIN_RENDERER_VIEW_PATHS], EXPECTED_PATHS);
  assert.deepEqual([...BRAIN_RENDERER_VIEW_PATHS], [...BRAIN_RENDERER_VIEW_PATHS].sort());
  assert.equal(new Set(BRAIN_RENDERER_VIEW_PATHS).size, 7);
  assert.ok(Object.isFrozen(BRAIN_RENDERER_VIEW_PATHS));
});

test('6. output paths equal BRAIN_RENDERER_VIEW_PATHS exactly and are ordered by path; Home.md is present', () => {
  const paths = render().map((f) => f.path);
  assert.deepEqual(paths, [...BRAIN_RENDERER_VIEW_PATHS]);
  assert.ok(paths.includes('DDAE-Brain/Home.md'));
});

test('7. no non-contract view is produced (Context-Packages, Architecture, Current-Session, Roadmap)', () => {
  const paths = render().map((f) => f.path).join('\n');
  for (const forbidden of ['Context-Packages', 'Architecture', 'Current-Session', 'Roadmap']) {
    assert.ok(!paths.includes(forbidden), forbidden);
  }
  assert.ok(!file(render(), 'Home.md').includes('Context-Packages'));
});

// ───────────────────────── paths / root ─────────────────────────

test('8. every output path lives under DDAE-Brain/ and never under .ddae/ or any dot-folder', () => {
  for (const { path: p } of render()) {
    assert.ok(p.startsWith('DDAE-Brain/'), p);
    assert.ok(!p.startsWith('.ddae/'), p);
    assert.ok(p.split('/').every((segment) => !segment.startsWith('.')), p);
  }
});

test('9. output paths are portable: forward slashes, relative, no drive, no backslash, no ..', () => {
  for (const { path: p } of render()) {
    assert.ok(!p.includes('\\'));
    assert.ok(!p.startsWith('/'));
    assert.ok(!/^[A-Za-z]:/.test(p));
    assert.ok(!p.split('/').includes('..'));
  }
});

test('10. no output leaks an absolute machine path', () => {
  for (const { content } of render()) {
    assert.ok(!/[A-Za-z]:[\\/]/.test(content));
    assert.ok(!content.includes('\\Users'));
    assert.ok(!content.includes('/home/'));
    assert.ok(!content.includes('/Users/'));
  }
});

// ───────────────────────── marker / line endings ─────────────────────────

test('11. every file: H1, blank line, the generated marker, exactly once', () => {
  for (const { path: p, content } of render()) {
    const lines = content.split('\n');
    assert.match(lines[0], /^# \S/, p);
    assert.equal(lines[1], '', p);
    assert.equal(lines[2], MARKER, p);
    assert.equal(content.split(MARKER).length, 2, `${p} contains the marker exactly once`);
  }
});

test('12. marker is static: no timestamp, version or fingerprint on the marker line, identical across manifests', () => {
  const a = render();
  const b = render({ release_state: { version: '9.9.9', latest_tag: 'v9.9.9' } }, { engineVersion: '7.7.7' });
  for (let i = 0; i < a.length; i += 1) {
    assert.equal(a[i].content.split('\n')[2], b[i].content.split('\n')[2]);
  }
});

test('13. LF only, exactly one final newline, no BOM (byte level)', () => {
  for (const { path: p, content } of render()) {
    assert.ok(!content.includes('\r'), p);
    assert.ok(content.endsWith('\n') && !content.endsWith('\n\n'), p);
    const bytes = Buffer.from(content, 'utf8');
    assert.equal(bytes[bytes.length - 1], 0x0a);
    assert.notEqual(bytes[bytes.length - 2], 0x0a);
    assert.notEqual(bytes[0], 0xef, 'no BOM');
    assert.equal(bytes[0], 0x23, 'starts with #');
  }
});

// ───────────────────────── links ─────────────────────────

test('14. links are Markdown relative links only — no wikilinks, no absolute or file: URLs', () => {
  for (const { path: p, content } of render()) {
    assert.ok(!content.includes('[['), p);
    assert.ok(!content.includes(']]'), p);
    for (const target of linkTargets(content)) {
      assert.ok(target.startsWith('./') || target.startsWith('../'), `${p}: ${target}`);
      assert.ok(!/^[a-z]+:/i.test(target), `${p}: ${target}`);
    }
  }
});

test('15. every link points to a generated view or to a manifest source (.md), resolved from DDAE-Brain/', () => {
  const manifest = compile();
  const sourcePaths = new Set(manifest.sources.map((s) => s.path));
  let checked = 0;
  for (const { content } of renderBrainWorkspace(manifest)) {
    for (const target of linkTargets(content)) {
      checked += 1;
      if (target.startsWith('./')) {
        assert.ok(BRAIN_RENDERER_VIEW_PATHS.includes(`${BRAIN_DIR}/${target.slice(2)}`), target);
      } else {
        const decoded = decodeURIComponent(target.slice(3));
        assert.ok(sourcePaths.has(decoded), target);
        assert.ok(decoded.endsWith('.md'), target);
      }
    }
  }
  assert.ok(checked > 10);
});

test('16. Home links to the six navigable views and each view links back to Home', () => {
  const files = render();
  const home = file(files, 'Home.md');
  for (const name of ['Sessions', 'Decisions', 'Risks', 'Bugs', 'Releases', 'Recent-Activity']) {
    assert.ok(home.includes(`](./${name}.md)`), name);
    assert.ok(file(files, `${name}.md`).includes('[← Home](./Home.md)'), name);
  }
  assert.ok(!home.includes('[← Home]'));
});

test('17. link destinations are percent-encoded per segment; unsafe paths fall back to inline code without a link', () => {
  const docs = 'Docs/dir with space/(a) b#c?d é.md';
  const files = render({
    decisions: [
      { id: 'RD-01', summary: 'encoded', source_path: docs },
      { id: 'RD-02', summary: 'not linkable', source_path: 'Docs/bad\nname.md' },
      { id: 'RD-03', summary: 'not markdown', source_path: 'Docs/data.json' },
      { id: 'RD-04', summary: 'backtick in name', source_path: 'Docs/a`b.md' },
    ],
  });
  const decisions = file(files, 'Decisions.md');
  assert.ok(decisions.includes('](../Docs/dir%20with%20space/%28a%29%20b%23c%3Fd%20%C3%A9.md)'));
  const line = (id) => decisions.split('\n').find((l) => l.includes(`\`${id}\``));
  assert.ok(!line('RD-02').includes(']('), 'control char in path → no link');
  assert.ok(line('RD-02').includes('`Docs/bad name.md`'));
  assert.ok(!line('RD-03').includes(']('), 'non-.md source is code only');
  assert.ok(line('RD-03').includes('`Docs/data.json`'));
  assert.ok(line('RD-04').includes('](../Docs/a%60b.md)'));
  assert.ok(line('RD-04').includes('``a`b.md``'), 'label uses a dynamic code fence');
});

// ───────────────────────── Home ─────────────────────────

test('18. Home shows the contract sections in fixed order, from the manifest only', () => {
  const home = file(render(), 'Home.md');
  const headings = home.split('\n').filter((l) => l.startsWith('## '));
  assert.deepEqual(headings, ['## Navigation', '## Project', '## Git', '## Current Session', '## Current Tasks', '## Release State', '## Provenance']);
  assert.ok(home.startsWith('# Project Brain\n'));
  assert.ok(home.includes('`demo-project`'));
  assert.ok(home.includes('HEAD: `' + 'a'.repeat(40) + '`'));
  assert.ok(home.includes('`session_02_beta`'));
  assert.ok(home.includes('`Write tests`') && home.includes('`Write code`'));
  assert.ok(home.includes('`1.2.3`'));
});

test('19. Home provenance shows schema_version, engine_version and the manifest fingerprint', () => {
  const manifest = compile();
  const home = file(renderBrainWorkspace(manifest), 'Home.md');
  assert.ok(home.includes('`brain-manifest-v1`'));
  assert.ok(home.includes(`\`${ENGINE_VERSION}\``));
  assert.ok(home.includes(`\`${manifest.fingerprint.value}\``));
});

test('20. generated_at is never rendered and never changes the output', () => {
  const plain = render();
  const stamped = render({}, { generatedAt: '2031-05-05T05:05:05.000Z' });
  assert.deepEqual(stamped, plain);
  for (const { content } of stamped) {
    assert.ok(!content.includes('2031-05-05'));
    assert.ok(!content.toLowerCase().includes('generated_at'));
  }
});

// ───────────────────────── individual views ─────────────────────────

test('21. Sessions lists ddae sessions, marks the current one and shows its status only', () => {
  const sessions = file(render(), 'Sessions.md');
  assert.ok(sessions.includes('`session_01_alpha`'));
  const current = sessions.split('\n').find((l) => l.includes('`session_02_beta`') && l.includes('(current)'));
  assert.ok(current);
  assert.ok(sessions.includes('`Em andamento`'));
  assert.equal(sessions.split('Em andamento').length, 2, 'status appears once (only for the current session)');
  assert.ok(sessions.includes('Blocks: 2'));
  assert.ok(sessions.includes('`02_analysis`'), 'missing module is named');
  assert.ok(!sessions.includes('README'), 'does not infer a session README');
});

test('22. Decisions / Risks / Bugs use only id, source_path and summary — no invented status', () => {
  const files = render();
  const decisions = file(files, 'Decisions.md');
  const risks = file(files, 'Risks.md');
  const bugs = file(files, 'Bugs.md');
  assert.ok(decisions.includes('`RD-01`: `First decision`'));
  assert.ok(risks.includes('`MR-01`: `A risk`'));
  assert.ok(bugs.includes('`BUG-01`: `Bug in alpha`') && bugs.includes('`BUG-01`: `Bug in beta`'));
  for (const text of [decisions, risks, bugs]) {
    assert.ok(!text.includes('Aberto'), 'snapshot status must not leak (not in Manifest v1)');
    assert.ok(!/\b(status|severity|owner|priority|date)\b/i.test(text.replace(MARKER, '')), 'no invented field labels');
  }
});

test('23. Releases renders exclusively release_state', () => {
  const releases = file(render(), 'Releases.md');
  assert.ok(releases.includes('`package_version`: `1.2.3`'));
  assert.ok(releases.includes('`latest_tag`: `v1.2.3`'));
  assert.ok(releases.includes('`package.json`'));
  assert.ok(!releases.includes('](../package.json)'), 'non-markdown source is not linked');
});

test('24. Recent-Activity preserves the manifest order (no re-sort) and states the ordering honestly', () => {
  // The schema already enforces canonical (SHA) order, so the received order IS that order.
  const manifest = clone(compile({ recent_changes: ['0', '9', 'a', 'f'].map((c) => ({ sha: c.repeat(40) })) }));
  const files = renderBrainWorkspace(manifest);
  const activity = file(files, 'Recent-Activity.md');
  const rendered = [...activity.matchAll(/`([0-9a-f]{40})`/g)].map((m) => m[1]);
  assert.deepEqual(rendered, manifest.entities.recent_changes.map((c) => c.id), 'same order as received');
  assert.ok(activity.includes('Ordered by commit SHA (deterministic).'));
  assert.ok(activity.includes('not a chronological history'));
  assert.ok(!/most recent|latest first|newest/i.test(activity));
});

// ───────────────────────── empty states ─────────────────────────

test('25. empty states are explicit and deterministic for every collection', () => {
  const files = render(EMPTY_SNAPSHOT);
  assert.ok(file(files, 'Decisions.md').includes('No decisions recorded.'));
  assert.ok(file(files, 'Risks.md').includes('No risks recorded.'));
  assert.ok(file(files, 'Bugs.md').includes('No open bugs recorded.'));
  assert.ok(file(files, 'Recent-Activity.md').includes('No recent changes available (Git unavailable or no commits).'));
  assert.ok(file(files, 'Releases.md').includes('No release information available.'));
  const home = file(files, 'Home.md');
  assert.ok(home.includes("No open tasks in the current session's latest block."));
  assert.ok(home.includes('No release information available.'));
  assert.deepEqual(render(EMPTY_SNAPSHOT), files);
});

test('26. Git unavailable → "Git: not available." and "HEAD: n/a"; no other Git source is consulted', () => {
  const home = file(render(EMPTY_SNAPSHOT), 'Home.md');
  assert.ok(home.includes('Git: not available.'));
  assert.ok(home.includes('HEAD: n/a'));
  const noCommits = file(render({ git: { available: true, repository: true, branch: 'main', head: null } }), 'Home.md');
  assert.ok(noCommits.includes('Git: available.'));
  assert.ok(noCommits.includes('HEAD: n/a'));
});

test('27. DDAE control plane missing and current session absent are distinct empty states', () => {
  const missing = render(EMPTY_SNAPSHOT);
  assert.ok(file(missing, 'Home.md').includes('DDAE control plane (Docs/) not found.'));
  assert.ok(file(missing, 'Sessions.md').includes('DDAE control plane (Docs/) not found.'));
  const noSession = render({
    ddae: { available: true, docs_root: 'Docs', sessions_root: 'Docs/05_sessions', sessions: [], current_session: null },
    current_session: null,
  });
  assert.ok(file(noSession, 'Home.md').includes('No canonical session found.'));
  assert.ok(file(noSession, 'Sessions.md').includes('No canonical session found.'));
  assert.ok(file(noSession, 'Sessions.md').includes('No sessions found.'));
  assert.ok(!file(noSession, 'Home.md').includes('control plane'));
});

test('28. a manifest with no entities at all renders 7 valid, non-empty documents', () => {
  const files = render(EMPTY_SNAPSHOT);
  assert.equal(files.length, 7);
  for (const { content } of files) assert.ok(content.length > 50);
});

// ───────────────────────── markdown safety ─────────────────────────

test('29. adversarial summaries stay inert: one line, dynamic fence, no structure injected', () => {
  const nasty = 'Use `code` and ``double`` | pipe [x](y) [[wiki]] <b>html</b> ---\n# heading\tTab sep\u0007bell ![img](x)';
  const normalized = 'Use `code` and ``double`` | pipe [x](y) [[wiki]] <b>html</b> --- # heading Tab sep bell ![img](x)';
  const files = render({ decisions: [{ id: 'RD-01', summary: nasty, source_path: 'Docs/04_governance/registro_decisoes.md' }] });
  const decisions = file(files, 'Decisions.md');
  const lines = decisions.split('\n');
  const entryLines = lines.filter((l) => l.includes('RD-01'));
  assert.equal(entryLines.length, 1, 'multiline summary collapses to a single line');
  assert.ok(entryLines[0].includes(`\`\`\`${normalized}\`\`\``), 'fence is longer than the longest backtick run in the content');
  const headings = lines.filter((l) => l.startsWith('#'));
  assert.deepEqual(headings, ['# Decisions', '## Index']);
  assert.ok(!/[\u0000-\u0008\u000b-\u001f\u007f\u2028\u2029]/.test(decisions));
  assert.equal(decisions.split('\n---').length, 1, 'no frontmatter/hr delimiter line is created');
});

test('30. ids, project name and paths containing backticks/wikilinks/HTML are rendered as inert inline code', () => {
  const files = render({
    project: { name: 'my `proj` [[x]] <i>', root_relative_path: '.' },
    risks: [{ id: 'R`1', summary: '   ', status: 'x', source_path: 'Docs/04_governance/matriz_riscos.md' }],
  });
  const home = file(files, 'Home.md');
  assert.ok(home.includes('Name: ``my `proj` [[x]] <i>``'));
  const risks = file(files, 'Risks.md');
  assert.ok(risks.includes('``R`1``'));
  assert.ok(!home.split('\n').some((l) => /^\s*\[\[/.test(l)));
});

test('31. long summaries are never truncated and special Unicode is preserved', () => {
  const long = `${'ação — ünïcödé 日本語 🙂 '.repeat(200)}end`;
  const decisions = file(render({ decisions: [{ id: 'RD-09', summary: long, source_path: 'Docs/x.md' }] }), 'Decisions.md');
  assert.ok(decisions.includes(long));
});

test('32. an empty summary is rendered as a valid code span, never dropped', () => {
  const decisions = file(render({ decisions: [{ id: 'RD-05', summary: '', source_path: 'Docs/x.md' }] }), 'Decisions.md');
  assert.ok(decisions.split('\n').some((l) => l.includes('`RD-05`')));
});

// ───────────────────────── manifest.views (transitional) ─────────────────────────

// Bloco 08 (D2) amended the last assertion of this test: the Renderer now derives Home's
// navigation from manifest.views, so "output does not depend on manifest.views" no longer
// holds for Home. Everything else it proved (never mutated or synchronized) is unchanged,
// and the six other views still do not depend on it.
test('33. manifest.views is never mutated or synchronized; only Home navigation consults it (D2)', () => {
  const emptyViews = clone(compile());
  assert.deepEqual(emptyViews.views, []);
  const filled = clone(emptyViews);
  filled.views = ['DDAE-Brain/Home.md'];
  const before = JSON.stringify(filled);
  const out1 = renderBrainWorkspace(emptyViews);
  const out2 = renderBrainWorkspace(filled);
  assert.equal(JSON.stringify(filled), before);
  assert.deepEqual(emptyViews.views, []);
  for (const entry of out1) {
    if (entry.path === 'DDAE-Brain/Home.md') continue;
    assert.deepEqual(out2.find((f) => f.path === entry.path), entry, 'views other than Home do not depend on manifest.views');
  }
});

test('34. TRANSITIONAL: the current Compiler emits views [] while the Renderer declares 7 paths — no runtime equality is required yet (closed in Bloco 08)', () => {
  const manifest = compile();
  assert.deepEqual([...manifest.views], []);
  assert.equal(renderBrainWorkspace(manifest).length, BRAIN_RENDERER_VIEW_PATHS.length);
});

// ───────────────────────── validation ─────────────────────────

test('35. an invalid manifest is rejected (via the existing schema), never "fixed"', () => {
  assert.throws(() => renderBrainWorkspace(null), /Brain Manifest/);
  assert.throws(() => renderBrainWorkspace({}), /Brain Manifest/);
  const broken = clone(compile());
  broken.schema_version = 'brain-manifest-v9';
  assert.throws(() => renderBrainWorkspace(broken), /schema_version/);
  const extra = clone(compile());
  extra.memory = [];
  assert.throws(() => renderBrainWorkspace(extra), /memory/);
});

// ───────────────────────── source guard ─────────────────────────

const readCode = (...segments) => fs.readFileSync(path.join(REPO_ROOT, ...segments), 'utf8')
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .replace(/^\s*\/\/.*$/gm, '');

test('36. the renderer is pure: no fs/network/clock/randomness/cwd/collectors/Claude-Mem/memory provider', () => {
  const code = readCode('src', 'workspace', 'renderer.js');
  for (const token of [
    'node:fs', 'fs/promises', 'node:child_process', 'node:http', 'node:https', 'node:net', 'fetch(',
    'Date.now', 'new Date', 'Math.random', 'randomUUID', 'process.cwd', 'process.env',
    'collectDdaeContext', 'collectGitContext', 'discoverWorkspaceState', 'compileBrainManifest',
    'writeFile', 'mkdirSync', 'wikilink',
  ]) {
    assert.ok(!code.includes(token), `renderer.js must not reference ${token}`);
  }
  const lower = code.toLowerCase();
  assert.ok(!lower.includes('claude-mem') && !lower.includes('memoryprovider'));
  const imports = [...code.matchAll(/from\s+'([^']+)'/g)].map((m) => m[1]);
  assert.deepEqual(imports.sort(), ['../schemas/brain-schema.js']);
});

// ───────────────────────── integration ─────────────────────────

function write(root, rel, content) {
  const abs = path.join(root, rel);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content, 'utf8');
}

function assertRealLinks(files, root) {
  let checked = 0;
  for (const { content } of files) {
    for (const target of linkTargets(content)) {
      if (target.startsWith('../')) {
        checked += 1;
        assert.ok(fs.existsSync(path.join(root, decodeURIComponent(target.slice(3)))), `dangling link ${target}`);
      }
    }
  }
  return checked;
}

test('37. integration: Discovery → Compiler → Renderer on a temp project — 7 views, real links, zero writes', () => {
  const dir = makeTempDir();
  try {
    write(dir, 'package.json', JSON.stringify({ name: 'demo', version: '3.1.4' }));
    write(dir, 'Docs/05_sessions/session_01_demo/README.md', '# Session\n\n## 5. Status\n\n- [ ] Não iniciada\n- [x] Em andamento\n');
    write(dir, 'Docs/05_sessions/session_01_demo/05_blocks/bloco_01_x.md', '# Bloco 01 — X\n\n- [ ] Do the `first` | thing\n');
    write(dir, 'Docs/04_governance/registro_decisoes.md', '# Registro\n\n### RD-01 — Pick `pipes | and` [[links]]\n\n- **Status:** Vigente\n');
    write(dir, 'Docs/04_governance/matriz_riscos.md', '# M\n\n| ID | Risco | Área | Probabilidade | Impacto | Status |\n|---|---|---|---|---|---|\n| MR-01 | Something `risky` | x | a | b | Aberto |\n');
    const list = () => fs.readdirSync(dir, { recursive: true }).sort();
    const before = list();
    const manifest = compileBrainManifest(discoverWorkspaceState(dir), { engineVersion: ENGINE_VERSION });
    const manifestJson = JSON.stringify(manifest);
    const files = renderBrainWorkspace(manifest);
    const again = renderBrainWorkspace(compileBrainManifest(discoverWorkspaceState(dir), { engineVersion: ENGINE_VERSION }));
    assert.deepEqual(files.map((f) => f.path), [...BRAIN_RENDERER_VIEW_PATHS]);
    assert.deepEqual(files, again);
    assert.equal(JSON.stringify(manifest), manifestJson, 'manifest not mutated');
    assert.deepEqual([...manifest.views], [], 'transitional: compiler still emits views []');
    assert.ok(file(files, 'Decisions.md').includes('``Pick `pipes | and` [[links]]``'));
    assert.ok(file(files, 'Risks.md').includes('`` Something `risky` ``'), 'content ending in a backtick gets a padded fence');
    assert.ok(file(files, 'Home.md').includes('``Do the `first` | thing``'));
    assert.ok(assertRealLinks(files, dir) >= 3);
    assert.deepEqual(list(), before, 'no filesystem write');
    assert.ok(!fs.existsSync(path.join(dir, 'DDAE-Brain')));
    assert.ok(!fs.existsSync(path.join(dir, '.ddae')));
  } finally {
    cleanup(dir);
  }
});

test('38. integration: the DDAE self-host renders 7 views with only real links and writes nothing', () => {
  const engineVersion = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'package.json'), 'utf8')).version;
  const brainDir = path.join(REPO_ROOT, 'DDAE-Brain');
  const machineDir = path.join(REPO_ROOT, '.ddae', 'brain');
  assert.ok(!fs.existsSync(brainDir) && !fs.existsSync(machineDir));
  const manifest = compileBrainManifest(discoverWorkspaceState(REPO_ROOT), { engineVersion });
  const files = renderBrainWorkspace(manifest);
  assert.deepEqual(files.map((f) => f.path), [...BRAIN_RENDERER_VIEW_PATHS]);
  assert.deepEqual(files, renderBrainWorkspace(manifest));
  assert.ok(assertRealLinks(files, REPO_ROOT) >= 1);
  for (const { content } of files) {
    assert.ok(!content.includes('[['));
    assert.ok(!/[A-Za-z]:[\\/]/.test(content));
  }
  assert.ok(!fs.existsSync(brainDir) && !fs.existsSync(machineDir), 'nothing written by rendering');
});

// ═══════════════════════════════════════════════════════════════════════════
// Bloco 05 — portable Markdown navigation hardening (adversarial characterization)
//
// These pin down the link generator (`source_path` → link or inert code) that
// Bloco 04 already implemented. They are characterization/regression tests: the
// renderer must keep classifying every adversarial path as either a safe,
// single-encoded, ../-prefixed relative link or inert inline code — never a
// clickable escape, scheme, or decoded traversal.
// ═══════════════════════════════════════════════════════════════════════════

const SAFE_DEST = /^\.\.\/[A-Za-z0-9._~%/-]+$/;
const pid = (index) => `P-${String(index + 1).padStart(3, '0')}`;

function renderPaths(paths) {
  const decisions = paths.map((p, i) => ({ id: pid(i), summary: `entry ${i + 1}`, source_path: p }));
  const files = render({ decisions });
  return { files, decisions: file(files, 'Decisions.md') };
}

function entryLine(markdown, index) {
  return markdown.split('\n').find((line) => line.includes(`\`${pid(index)}\``));
}

/** Decodes a link destination exactly once, per segment (what a consumer's single URL-decode yields). */
function decodeOnce(destination) {
  return destination.slice(3).split('/').map((segment) => decodeURIComponent(segment));
}

test('39. literal traversal / dot / empty segments in source_path never become a link (inert code instead)', () => {
  const paths = ['Docs/../secrets.md', '../outside.md', '../../outside.md', 'Docs/../../../etc/passwd.md', 'Docs/a/../b.md', 'Docs/./a.md', './a.md', 'Docs//a.md', 'Docs/..'];
  const { decisions } = renderPaths(paths);
  paths.forEach((p, i) => {
    const line = entryLine(decisions, i);
    assert.ok(line, p);
    assert.ok(!line.includes(']('), `${p} must not be linked`);
    assert.ok(line.includes(`\`${p}\``), `${p} is shown as inert code`);
  });
  assert.equal(linkTargets(decisions).filter((t) => t.startsWith('../')).length, 0);
});

test('40. encoded traversal (%2e%2e, %2E%2E, %2e., .%2e) is only ever a literal, single-encoded name — never a decoded ..', () => {
  const cases = [
    ['%2e%2e/secret.md', '../%252e%252e/secret.md'],
    ['%2E%2E/secret.md', '../%252E%252E/secret.md'],
    ['%2e./x.md', '../%252e./x.md'],
    ['.%2e/x.md', '../.%252e/x.md'],
    ['Docs/%2e%2e/x.md', '../Docs/%252e%252e/x.md'],
    ['%2e%2e%2fsecret.md', '../%252e%252e%252fsecret.md'],
  ];
  const { decisions } = renderPaths(cases.map(([p]) => p));
  cases.forEach(([original, expected], i) => {
    const line = entryLine(decisions, i);
    assert.ok(line.includes(`](${expected})`), `${original} → ${expected}`);
    const destination = expected;
    assert.ok(!/(?<!%25)%2e/i.test(destination), 'a raw %2e never survives encoding');
    assert.deepEqual(decodeOnce(destination).join('/'), original, 'one decode gives back the original text, not ..');
    assert.ok(!decodeOnce(destination).some((s) => s === '..' || s === '.'), 'no traversal segment after one decode');
    assert.ok(!destination.includes('/../'));
  });
});

test('41. double encoding: an already-encoded name is encoded exactly once more — never decoded, normalized or re-encoded', () => {
  const { decisions } = renderPaths(['Docs/%252e%252e/x.md', 'Docs/%2F%5C.md']);
  assert.ok(entryLine(decisions, 0).includes('](../Docs/%25252e%25252e/x.md)'));
  assert.ok(entryLine(decisions, 1).includes('](../Docs/%252F%255C.md)'));
});

test('42. scheme-like values never yield an external or scheme link (":" is always encoded, dest always ../-prefixed)', () => {
  const paths = ['http://evil.example/a.md', 'https://evil.example/a.md', 'javascript:alert(1).md', 'JaVaScRiPt:x.md', 'file:///etc/passwd.md', 'data:text/html,x.md', 'mailto:a@b.md', 'C:x.md', 'Docs/a:b.md'];
  const { files, decisions } = renderPaths(paths);
  assert.ok(entryLine(decisions, 0).includes('`http://evil.example/a.md`') && !entryLine(decisions, 0).includes(']('), 'empty segment → inert code');
  assert.ok(!entryLine(decisions, 4).includes(']('), 'file:/// → inert code');
  assert.ok(entryLine(decisions, 2).includes('](../javascript%3Aalert%281%29.md)'));
  assert.ok(entryLine(decisions, 7).includes('](../C%3Ax.md)'));
  for (const { content } of files) {
    for (const target of linkTargets(content)) {
      assert.ok(!target.includes(':'), target);
      assert.ok(target.startsWith('./') || target.startsWith('../'), target);
    }
    assert.ok(!/\]\((?:https?|javascript|file|data|mailto):/i.test(content));
  }
});

test('43. Unicode look-alikes for . / \\ : are inert text — not traversal, separators or schemes — and are not normalized', () => {
  const dotLeader = 'Docs/\u2024\u2024/x.md';
  const ellipsis = 'Docs/\u2026/x.md';
  const fullwidthDots = 'Docs/\uFF0E\uFF0E/x.md';
  const fullwidthSlash = 'Docs\uFF0F..\uFF0Fx.md';
  const fullwidthBackslash = 'Docs\uFF3Ca.md';
  const fullwidthColon = 'javascript\uFF1Ax.md';
  const divisionSlash = 'Docs/a\u2215b.md';
  const rtlOverride = 'Docs/\u202Egnp.md';
  const paths = [dotLeader, ellipsis, fullwidthDots, fullwidthSlash, fullwidthBackslash, fullwidthColon, divisionSlash, rtlOverride];
  const { decisions } = renderPaths(paths);
  paths.forEach((original, i) => {
    const line = entryLine(decisions, i);
    const destination = linkTargets(line)[0];
    assert.ok(destination, `${JSON.stringify(original)} is an ordinary (non-traversal) name and links`);
    assert.match(destination, SAFE_DEST, 'destination is pure ASCII percent-encoding');
    assert.equal(decodeOnce(destination).join('/'), original, 'no Unicode normalization');
    assert.equal(destination.slice(3).split('/').length, original.split('/').length, 'look-alike slashes are not separators');
    assert.ok(!decodeOnce(destination).some((s) => s === '.' || s === '..' || s === ''));
  });
});

test('44. "%" and malformed escapes never break encoding or throw', () => {
  const { decisions } = renderPaths(['Docs/100%.md', 'Docs/%zz.md', 'Docs/%.md', '%%%.md', 'Docs/a%2Fb.md', 'Docs/a%00b.md']);
  assert.ok(entryLine(decisions, 0).includes('](../Docs/100%25.md)'));
  assert.ok(entryLine(decisions, 1).includes('](../Docs/%25zz.md)'));
  assert.ok(entryLine(decisions, 2).includes('](../Docs/%25.md)'));
  assert.ok(entryLine(decisions, 3).includes('](../%25%25%25.md)'));
  assert.ok(entryLine(decisions, 4).includes('](../Docs/a%252Fb.md)'), 'encoded separator text stays one segment');
  assert.ok(entryLine(decisions, 5).includes('](../Docs/a%2500b.md)'), 'encoded NUL text is literal text, not a control char');
});

test('45. brackets, parentheses, backticks, spaces, # ? < > quotes are all percent-encoded in destinations', () => {
  const { decisions } = renderPaths(['Docs/[x] (y) `z` #h ?q.md', 'Docs/<b>&amp;.md', 'Docs/"q" it\'s.md']);
  assert.ok(entryLine(decisions, 0).includes('](../Docs/%5Bx%5D%20%28y%29%20%60z%60%20%23h%20%3Fq.md)'));
  for (let i = 0; i < 3; i += 1) {
    assert.match(linkTargets(entryLine(decisions, i))[0], SAFE_DEST);
  }
});

test('46. control characters and lone surrogates in source_path: no link, no raw control in output, no exception', () => {
  const controls = ['\u0000', '\n', '\r', '\t', '\u001b', '\u007f', '\u0085', '\u2028', '\u2029'];
  const paths = [...controls.map((c) => `Docs/a${c}b.md`), 'Docs/\uD800.md'];
  const { files, decisions } = renderPaths(paths);
  paths.forEach((p, i) => {
    const line = entryLine(decisions, i);
    assert.ok(line, JSON.stringify(p));
    assert.ok(!line.includes(']('), `${JSON.stringify(p)} must not be linked`);
  });
  for (const { content } of files) {
    assert.ok(!/[\u0000-\u0009\u000b-\u001f\u007f-\u009f\u2028\u2029]/.test(content));
    assert.ok(!content.includes('\r'));
  }
  assert.equal(decisions.split('\n').filter((l) => /`entry \d+`/.test(l)).length, paths.length, 'each entry stays on exactly one line');
});

test('47. absolute, Windows-drive, backslash and UNC source paths are rejected before rendering (Schema), not rendered', () => {
  const rejected = ['/etc/passwd.md', 'C:/Users/x/a.md', 'C:\\Users\\x\\a.md', 'Docs\\a.md', '\\\\server\\share\\a.md', '//server/share/a.md'];
  for (const p of rejected) {
    assert.throws(() => compile({ decisions: [{ id: 'RD-01', summary: 's', source_path: p }] }), /source_path/, p);
    const manifest = clone(compile());
    manifest.entities.decisions[0].source_path = p;
    assert.throws(() => renderBrainWorkspace(manifest), /source_path/, `renderer rejects ${p}`);
  }
});

test('48. link eligibility requires membership in manifest.sources and a .md name (hand-built manifests)', () => {
  const noSources = clone(compile());
  noSources.sources = [];
  const withoutLinks = renderBrainWorkspace(noSources);
  for (const { content } of withoutLinks) {
    assert.equal(linkTargets(content).filter((t) => t.startsWith('../')).length, 0, 'no source known → nothing linked');
  }
  assert.ok(file(withoutLinks, 'Decisions.md').includes('`Docs/04_governance/registro_decisoes.md`'), 'path is still shown, inert');

  const partial = clone(compile());
  partial.sources = partial.sources.filter((s) => s.entity === 'decisions');
  const partialFiles = renderBrainWorkspace(partial);
  assert.ok(linkTargets(file(partialFiles, 'Decisions.md')).some((t) => t.startsWith('../')));
  assert.equal(linkTargets(file(partialFiles, 'Risks.md')).filter((t) => t.startsWith('../')).length, 0);
});

const CORPUS = [
  'Docs/../secrets.md', '../outside.md', 'Docs/./a.md', 'Docs//a.md', 'Docs/a/../b.md',
  '%2e%2e/secret.md', '%2E%2E/secret.md', '%2e./x.md', '.%2e/x.md', 'Docs/%2e%2e/x.md', '%2e%2e%2fsecret.md',
  'Docs/%252e%252e/x.md', '%252e%252e%252fx.md',
  'http://evil.example/a.md', 'javascript:alert(1).md', 'JaVaScRiPt:x.md', 'file:///etc/passwd.md', 'data:text/html,x.md', 'mailto:a@b.md', 'C:x.md', 'Docs/a:b.md',
  'Docs/100%.md', 'Docs/%zz.md', '%%%.md', 'Docs/a%2Fb.md', 'Docs/a%5Cb.md', 'Docs/a%00b.md',
  'Docs/[x] (y) `z` #h ?q.md', 'Docs/<b>&amp;.md', 'Docs/"q" it\'s.md',
  'Docs/\u2024\u2024/x.md', 'Docs/\u2026/x.md', 'Docs/\uFF0E\uFF0E/x.md', 'Docs\uFF0F..\uFF0Fx.md', 'Docs\uFF3Ca.md', 'javascript\uFF1Ax.md', 'Docs/a\u2215b.md', 'Docs/\u202Egnp.md',
  'Docs/\uD800.md', 'Docs/a\u0000b.md', 'Docs/a\nb.md', 'Docs/a\tb.md', 'Docs/a\u007fb.md', 'Docs/a\u0085b.md', 'Docs/a\u2028b.md',
  'Docs/ leading.md', 'Docs/trailing .md', 'Docs/ .md', 'Docs/x.MD', 'Docs/x.md/', 'Docs/x.txt', 'Docs/..',
  'Docs/café ação 日本語 🙂.md',
];
const MUST_NOT_LINK = new Set([
  'Docs/../secrets.md', '../outside.md', 'Docs/./a.md', 'Docs//a.md', 'Docs/a/../b.md', 'http://evil.example/a.md', 'file:///etc/passwd.md',
  'Docs/\uD800.md', 'Docs/a\u0000b.md', 'Docs/a\nb.md', 'Docs/a\tb.md', 'Docs/a\u007fb.md', 'Docs/a\u0085b.md', 'Docs/a\u2028b.md',
  'Docs/x.MD', 'Docs/x.md/', 'Docs/x.txt', 'Docs/..',
]);

test('49. property over an adversarial corpus: every generated link is ../-prefixed, pure-ASCII, single-encoded and maps back to a known .md source', () => {
  const manifest = compile({ decisions: CORPUS.map((p, i) => ({ id: pid(i), summary: `entry ${i + 1}`, source_path: p })) });
  const files = renderBrainWorkspace(manifest);
  const known = new Set(manifest.sources.map((source) => source.path));
  const linked = new Set();
  for (const { content } of files) {
    for (const target of linkTargets(content)) {
      if (target.startsWith('./')) {
        assert.ok(BRAIN_RENDERER_VIEW_PATHS.includes(`${BRAIN_DIR}/${target.slice(2)}`), target);
        continue;
      }
      assert.match(target, SAFE_DEST, target);
      assert.ok(!target.includes(':') && !target.includes('\\'), target);
      const segments = decodeOnce(target);
      assert.ok(!segments.some((s) => s === '' || s === '.' || s === '..'), target);
      const original = segments.join('/');
      assert.ok(known.has(original), `dangling/invented link ${target}`);
      assert.ok(original.endsWith('.md'), original);
      linked.add(original);
    }
  }
  for (const forbidden of MUST_NOT_LINK) {
    assert.ok(!linked.has(forbidden), `must not link ${JSON.stringify(forbidden)}`);
  }
  for (const expected of ['Docs/café ação 日本語 🙂.md', '%2e%2e/secret.md', 'javascript:alert(1).md', 'Docs/\u202Egnp.md', 'Docs/ leading.md']) {
    assert.ok(linked.has(expected), `should link ${JSON.stringify(expected)}`);
  }
});

test('50. adversarial manifests render byte-identically every time and never throw', () => {
  const a = renderPaths(CORPUS).files;
  const b = renderPaths(CORPUS).files;
  assert.deepEqual(a, b);
  for (let i = 0; i < a.length; i += 1) {
    assert.ok(Buffer.from(a[i].content, 'utf8').equals(Buffer.from(b[i].content, 'utf8')));
  }
  for (const { content } of a) {
    assert.ok(content.endsWith('\n') && !content.endsWith('\n\n') && !content.includes('\r'));
  }
});

test('51. navigation is symmetric and independent of entity data: Home ↔ 6 views, every view reachable, no dangling view link', () => {
  const graphOf = (files) => {
    const graph = new Map();
    for (const { path: p, content } of files) {
      graph.set(p, linkTargets(content).filter((t) => t.startsWith('./')).map((t) => `${BRAIN_DIR}/${t.slice(2)}`));
    }
    return graph;
  };
  const normal = graphOf(render());
  const adversarial = graphOf(renderPaths(CORPUS).files);
  const empty = graphOf(render(EMPTY_SNAPSHOT));
  for (const graph of [normal, adversarial, empty]) {
    const home = `${BRAIN_DIR}/Home.md`;
    const others = BRAIN_RENDERER_VIEW_PATHS.filter((p) => p !== home);
    assert.equal(others.length, 6);
    assert.deepEqual([...graph.get(home)].sort(), [...others].sort(), 'Home links to the six views, once each, never to itself');
    for (const view of others) {
      assert.deepEqual(graph.get(view), [home], `${view} links back to Home exactly once and to nothing else`);
    }
    const seen = new Set([home]);
    const queue = [home];
    while (queue.length > 0) {
      for (const next of graph.get(queue.shift())) {
        assert.ok(BRAIN_RENDERER_VIEW_PATHS.includes(next), `dangling view link ${next}`);
        if (!seen.has(next)) { seen.add(next); queue.push(next); }
      }
    }
    assert.equal(seen.size, 7, 'all seven views reachable from Home');
  }
  assert.deepEqual([...adversarial.entries()], [...normal.entries()], 'entity data never changes the navigation graph');
});

test('52. portable Markdown only: no frontmatter, wikilinks, Obsidian URIs, Dataview, backslashes or drive letters in any output', () => {
  for (const { content } of [...render(), ...renderPaths(CORPUS).files]) {
    assert.ok(content.startsWith('# '), 'first line is the H1 — no frontmatter block');
    assert.ok(!content.split('\n').some((line) => line === '---'), 'no frontmatter/hr delimiter line');
    assert.ok(!stripCode(content).includes('[['), 'no wikilink outside inert code');
    assert.ok(!/obsidian:\/\/|app:\/\//i.test(stripCode(content)));
    assert.ok(!/dataview/i.test(stripCode(content)));
    for (const target of linkTargets(content)) {
      assert.ok(!target.includes('\\') && !/^[A-Za-z]:/.test(target));
    }
  }
});

test('53. source guard: the link generator never decodes or normalizes, has no Obsidian coupling and imports only the schema', () => {
  const code = readCode('src', 'workspace', 'renderer.js');
  for (const token of ['decodeURI', 'decodeURIComponent', 'unescape(', '.normalize(', 'obsidian://', 'app://', 'dataview', 'frontmatter', "from 'node:path'", "from 'path'", 'process.platform']) {
    assert.ok(!code.toLowerCase().includes(token.toLowerCase()), `renderer.js must not contain ${token}`);
  }
});

test('54. KNOWN LIMITATION (P4, documented not fixed): bidi controls are preserved verbatim inside inert code spans and percent-encoded in link destinations', () => {
  // Contract: summaries are extracted verbatim and never sanitized aggressively. Bidi
  // controls are not Markdown structure, so they cannot create links or headings; whether
  // they should be neutralized for visual-spoofing reasons is a Bloco 09 (security) decision.
  const bidi = '‮⁦⁩';
  const { decisions } = renderPaths([`Docs/a${bidi}b.md`]);
  assert.ok(decisions.includes('](../Docs/a%E2%80%AE%E2%81%A6%E2%81%A9b.md)'), 'destination is ASCII percent-encoding of the exact bytes');
  assert.ok(decisions.includes(`[\`a${bidi}b.md\`]`), 'the label keeps the bidi controls verbatim, inside a code span');
  const headings = decisions.split('\n').filter((l) => l.startsWith('#'));
  assert.deepEqual(headings, ['# Decisions', '## Index'], 'no structure is created by them');
});


// ───────────── Bloco 08, Fase A — navigation derived from manifest.views (D2) ─────────────

const FULL_VIEWS = [...EXPECTED_PATHS, 'DDAE-Brain/Context-Packages.md'].sort();

test('D2 legacy: manifest.views = [] renders the 7 views byte-identical to the Bloco 04 output', () => {
  // Captured from the renderer before Bloco 08 (sha256 of every file, and of the whole set).
  const legacy = {
    'DDAE-Brain/Bugs.md': '231294b856872087dc0df382f1ea3ec347c8eae9ceb84c4e74cad7b02c3e8b50',
    'DDAE-Brain/Decisions.md': 'fad28b6c7e2cd36257abf98c5f4eff06480647fc33a13a39bf87a1825a498769',
    'DDAE-Brain/Home.md': '0ef85e60812d15f37a1ebd5c047391356ac993bbd8497cfb0c9b6ac60699a3ae',
    'DDAE-Brain/Recent-Activity.md': 'd7396829aac725c08ec2c962a304f236560f7109c952967caff19c33bf1324c8',
    'DDAE-Brain/Releases.md': 'ef9d3596785285cc519cc465d54a1eea895d1c11a44553bd39547ba1de3b893f',
    'DDAE-Brain/Risks.md': '19e7aa0c861b21eab1e62b8cd25b0ec21844666417b437c0df5ff335bd98b718',
    'DDAE-Brain/Sessions.md': 'a80efc8aabb001e847642b8acfcb879cca2e2c10387976677d86443f6440c93d',
  };
  const files = render();
  assert.equal(files.length, 7);
  for (const entry of files) {
    assert.equal(createHash('sha256').update(entry.content).digest('hex'), legacy[entry.path], entry.path);
  }
});

test('D2: with the 8 declared views, Home links Context Packages after the six legacy links', () => {
  const home = file(render({}, { views: FULL_VIEWS }), 'Home.md');
  assert.ok(home.includes('- [Context Packages](./Context-Packages.md)'));
  const nav = home.split('\n').filter((line) => line.startsWith('- [') && line.includes('](./'));
  assert.deepEqual(nav, [
    '- [Sessions](./Sessions.md)',
    '- [Decisions](./Decisions.md)',
    '- [Risks](./Risks.md)',
    '- [Bugs](./Bugs.md)',
    '- [Releases](./Releases.md)',
    '- [Recent Activity](./Recent-Activity.md)',
    '- [Context Packages](./Context-Packages.md)',
  ]);
});

test('D2: only Home changes when views are declared — the six other views stay byte-identical', () => {
  const legacy = render();
  const full = render({}, { views: FULL_VIEWS });
  for (const entry of legacy) {
    if (entry.path === 'DDAE-Brain/Home.md') continue;
    assert.equal(full.find((f) => f.path === entry.path).content, entry.content, entry.path);
  }
});

test('D2: declared views are the canonical navigable set — an undeclared view is not linked', () => {
  const home = file(render({}, { views: ['DDAE-Brain/Home.md', 'DDAE-Brain/Sessions.md'] }), 'Home.md');
  assert.ok(home.includes('](./Sessions.md)'));
  for (const gone of ['Decisions', 'Risks', 'Bugs', 'Releases', 'Recent-Activity', 'Context-Packages']) {
    assert.ok(!home.includes(`](./${gone}.md)`), gone);
  }
});

test('D2: a declared view that is not a plain sibling Markdown file under DDAE-Brain/ is never linked', () => {
  const unsafe = [
    'DDAE-Brain/sub/Nested.md',
    'DDAE-Brain/Weird(Name).md',
    'DDAE-Brain/with space.md',
    'DDAE-Brain/not-markdown.txt',
    'Other/Elsewhere.md',
    'https://example.com/x.md',
    'DDAE-Brain/.hidden.md',
  ];
  const home = file(render({}, { views: ['DDAE-Brain/Home.md', ...unsafe] }), 'Home.md');
  for (const link of linkTargets(home)) {
    assert.ok(!unsafe.some((u) => link.includes(u.replace('DDAE-Brain/', ''))), link);
  }
  assert.ok(!home.includes('example.com'));
});

test('D2: the renderer stays pure and independent of any producer (no import of context-packages, no I/O)', () => {
  const source = fs.readFileSync(path.join(REPO_ROOT, 'src', 'workspace', 'renderer.js'), 'utf8');
  const imports = [...source.matchAll(/^import .* from '([^']+)'/gm)].map((m) => m[1]);
  assert.deepEqual(imports, ['../schemas/brain-schema.js']);
  assert.ok(!/context-packages/.test(source.replace(/^\s*\/\/.*$/gm, '')));
});

test('D2: with declared views the output is deterministic, the manifest is not mutated (also deeply frozen)', () => {
  const manifest = deepFreeze(compile({}, { views: FULL_VIEWS }));
  const before = JSON.stringify(manifest);
  const a = renderBrainWorkspace(manifest);
  const b = renderBrainWorkspace(manifest);
  assert.deepEqual(a, b);
  assert.equal(JSON.stringify(manifest), before);
});

test('D2: every link Home emits for declared views resolves to a declared view path', () => {
  const home = file(render({}, { views: FULL_VIEWS }), 'Home.md');
  for (const link of linkTargets(home).filter((l) => l.startsWith('./'))) {
    assert.ok(FULL_VIEWS.includes(`DDAE-Brain/${link.slice(2)}`), link);
  }
});
