import { assertBrainManifest, compareStrings } from '../schemas/brain-schema.js';

// Brain Workspace Renderer — a pure function from a validated Brain Manifest
// v1 to the human-readable views of the Project Brain, held in memory:
//
//   Brain Manifest v1  ──►  [{ path, content }]   (paths under DDAE-Brain/)
//
// It never collects, never compiles, never touches the fingerprint or
// `manifest.views`, and never reads or writes the filesystem — writing the
// returned files is the CLI's job (Bloco 08). The Manifest is its only
// input: no clock, no randomness, no cwd, no Git, no `Docs/`.
//
// Contract: Docs/03_contracts/contrato_workspace_project_brain.md, Seções D
// e D.1 (Amendment 1, DT-03): root `DDAE-Brain/`, generated-file marker
// right after the H1, relative Markdown links (no wikilinks), LF, exactly
// one trailing newline.
//
// Everything that originates in `Docs/` (ids, summaries, names, paths) is
// data, never structure: it is only ever emitted inside an inline code span
// whose fence is longer than any backtick run in the value, after control
// characters and line separators are collapsed to a single space. Nothing
// is truncated.

export const BRAIN_DIR = 'DDAE-Brain';

// Declared here, sorted by code point, so the Orchestrator can collect the
// view set (contract B.1). The Renderer never compares them with
// `manifest.views` — that invariant belongs to the Orchestrator.
const VIEW_NAMES = ['Bugs', 'Decisions', 'Home', 'Recent-Activity', 'Releases', 'Risks', 'Sessions'];
export const BRAIN_RENDERER_VIEW_PATHS = Object.freeze(VIEW_NAMES.map((name) => `${BRAIN_DIR}/${name}.md`));

const MARKER = '_Generated by DDAE. Derived from Docs/ and Git. Do not edit directly._';
const HOME_LINK = '[← Home](./Home.md)';
const PARENT_PREFIX = '../'.repeat(BRAIN_DIR.split('/').length);

const CONTROL_RUNS = /[\u0000-\u001f\u007f-\u009f\u2028\u2029]+/g;
const HAS_CONTROL = /[\u0000-\u001f\u007f-\u009f\u2028\u2029]/;

const EMPTY = Object.freeze({
  decisions: 'No decisions recorded.',
  risks: 'No risks recorded.',
  bugs: 'No open bugs recorded.',
  tasks: "No open tasks in the current session's latest block.",
  changes: 'No recent changes available (Git unavailable or no commits).',
  session: 'No canonical session found.',
  sessions: 'No sessions found.',
  ddae: 'DDAE control plane (Docs/) not found.',
  release: 'No release information available.',
});

function collapse(value) {
  return String(value ?? '').replace(CONTROL_RUNS, ' ').trim();
}

/** Inline code span; the fence is longer than any backtick run inside. */
function code(value) {
  const text = collapse(value);
  const longestRun = (text.match(/`+/g) ?? []).reduce((max, run) => Math.max(max, run.length), 0);
  const fence = '`'.repeat(longestRun + 1);
  const needsPadding = text === '' || text.startsWith('`') || text.endsWith('`');
  return needsPadding ? `${fence} ${text} ${fence}` : `${fence}${text}${fence}`;
}

function encodeSegment(segment) {
  return encodeURIComponent(segment).replace(/[!'()*]/g, (c) => `%${c.charCodeAt(0).toString(16).toUpperCase()}`);
}

/** Relative link destination from DDAE-Brain/ to a project path, or null when it cannot be expressed safely. */
function docsDestination(sourcePath, knownSources) {
  if (typeof sourcePath !== 'string' || !knownSources.has(sourcePath) || !sourcePath.endsWith('.md') || HAS_CONTROL.test(sourcePath)) {
    return null;
  }
  const segments = sourcePath.split('/');
  if (segments.some((segment) => segment === '' || segment === '.' || segment === '..')) {
    return null;
  }
  try {
    return `${PARENT_PREFIX}${segments.map(encodeSegment).join('/')}`;
  } catch {
    return null;
  }
}

function sourceRef(sourcePath, knownSources) {
  if (sourcePath === null) {
    return null;
  }
  const destination = docsDestination(sourcePath, knownSources);
  if (destination === null) {
    return code(sourcePath);
  }
  return `[${code(sourcePath.slice(sourcePath.lastIndexOf('/') + 1))}](${destination})`;
}

/** One bullet per manifest reference: source (link or code), then id and summary. */
function entityItem(entry, knownSources) {
  const identity = entry.summary === entry.id ? code(entry.id) : `${code(entry.id)}: ${code(entry.summary)}`;
  const source = sourceRef(entry.source_path, knownSources);
  return source === null ? `- ${identity}` : `- ${source} — ${identity}`;
}

function entityList(entries, emptyText, knownSources) {
  return entries.length === 0 ? emptyText : entries.map((entry) => entityItem(entry, knownSources)).join('\n');
}

function section(title, ...blocks) {
  return `## ${title}\n\n${blocks.join('\n\n')}`;
}

function document(title, { backLink = true } = {}, ...sections) {
  const parts = [`# ${title}`, MARKER];
  if (backLink) {
    parts.push(HOME_LINK);
  }
  return `${[...parts, ...sections].join('\n\n')}\n`;
}

function viewLink(name, label) {
  return `[${label}](./${name}.md)`;
}

function gitLines(manifest) {
  return [
    manifest.git.available ? '- Git: available.' : '- Git: not available.',
    `- HEAD: ${manifest.git.head ? code(manifest.git.head) : 'n/a'}`,
  ].join('\n');
}

function currentSessionBlock(manifest, { detailed }) {
  if (!manifest.ddae.available) {
    return EMPTY.ddae;
  }
  if (manifest.current_session === null) {
    return EMPTY.session;
  }
  const detail = manifest.ddae.current_session;
  const lines = [
    `- Session: ${code(manifest.current_session.id)}`,
    `- Selected: ${code(manifest.current_session.selection_reason)}`,
    `- Status: ${detail && detail.status ? code(detail.status) : 'n/a'}`,
  ];
  if (detailed && detail) {
    const present = detail.modules.filter((module) => module.exists).length;
    const missing = detail.modules.filter((module) => !module.exists).map((module) => code(module.name));
    lines.push(
      `- Path: ${code(detail.path)}`,
      `- Blocks: ${detail.counts.blocks}`,
      `- Prompts: ${detail.counts.prompts}`,
      `- Feedbacks: ${detail.counts.feedbacks}`,
      `- Modules: ${present}/${detail.modules.length} present`,
    );
    if (missing.length > 0) {
      lines.push(`- Missing modules: ${missing.join(', ')}`);
    }
  }
  return lines.join('\n');
}

// Home's navigation order for the views this module itself produces (Bloco 04).
const LEGACY_NAV = Object.freeze([
  ['Sessions', 'Sessions'],
  ['Decisions', 'Decisions'],
  ['Risks', 'Risks'],
  ['Bugs', 'Bugs'],
  ['Releases', 'Releases'],
  ['Recent-Activity', 'Recent Activity'],
]);
const SAFE_VIEW_NAME = /^[A-Za-z0-9][A-Za-z0-9_-]*$/;

/**
 * Home's navigation entries `[name, label]`. With `manifest.views = []` (the
 * legacy Bloco 03/04 state) it is exactly the six original links. Once views
 * are declared, `manifest.views` is the canonical navigable set (Bloco 08,
 * D2): the legacy entries that are declared come first, in their original
 * order, then any other declared view (e.g. `Context-Packages`) in manifest
 * order. Only plain sibling `DDAE-Brain/<Name>.md` files are ever linked; the
 * Renderer never learns which module produced a view.
 */
function navigationEntries(manifest) {
  if (manifest.views.length === 0) {
    return LEGACY_NAV;
  }
  const prefix = `${BRAIN_DIR}/`;
  const declared = manifest.views
    .filter((view) => view.startsWith(prefix) && view.endsWith('.md'))
    .map((view) => view.slice(prefix.length, -'.md'.length))
    .filter((name) => SAFE_VIEW_NAME.test(name) && name !== 'Home');
  const declaredNames = new Set(declared);
  const legacyNames = new Set(LEGACY_NAV.map(([name]) => name));
  const legacy = LEGACY_NAV.filter(([name]) => declaredNames.has(name));
  const extra = declared.filter((name) => !legacyNames.has(name)).map((name) => [name, name.replace(/-/g, ' ')]);
  return [...legacy, ...extra];
}

function renderHome(manifest, known) {
  const e = manifest.entities;
  return document(
    'Project Brain',
    { backLink: false },
    section('Navigation', navigationEntries(manifest).map(([name, label]) => `- ${viewLink(name, label)}`).join('\n')),
    section('Project', `- Name: ${code(manifest.project.name)}\n- Root: ${code(manifest.project.root_relative_path)}`),
    section('Git', gitLines(manifest)),
    section('Current Session', currentSessionBlock(manifest, { detailed: false })),
    section('Current Tasks', entityList(e.current_tasks, EMPTY.tasks, known)),
    section('Release State', entityList(e.release_state, EMPTY.release, known)),
    section(
      'Provenance',
      [
        `- Schema: ${code(manifest.schema_version)}`,
        `- Engine: ${code(manifest.engine_version)}`,
        `- Fingerprint (${manifest.fingerprint.algorithm}): ${code(manifest.fingerprint.value)}`,
      ].join('\n'),
    ),
  );
}

function renderSessions(manifest) {
  const currentName = manifest.ddae.current_session ? manifest.ddae.current_session.name : null;
  const all = manifest.ddae.sessions.length === 0
    ? (manifest.ddae.available ? EMPTY.sessions : EMPTY.ddae)
    : manifest.ddae.sessions
      .map((session) => `- ${code(session.name)} — ${code(session.path)}${session.name === currentName ? ' (current)' : ''}`)
      .join('\n');
  return document(
    'Sessions',
    {},
    section('Current Session', currentSessionBlock(manifest, { detailed: true })),
    section('All Sessions', all),
  );
}

function renderIndex(title, heading, description, entries, emptyText, known) {
  return document(title, {}, section(heading, description, entityList(entries, emptyText, known)));
}

function renderRecentActivity(manifest, known) {
  const note = 'Ordered by commit SHA (deterministic). Commit dates and subjects are not part of Manifest v1; this list is not a chronological history.';
  return document(
    'Recent Activity',
    {},
    section('Recent Changes', note, entityList(manifest.entities.recent_changes, EMPTY.changes, known)),
  );
}

/**
 * Renders the Project Brain views of `manifest` as an ordered, frozen list of
 * `{ path, content }` (paths relative to the project root, under
 * `DDAE-Brain/`). Rejects an invalid Manifest (via the existing schema)
 * rather than repairing it. Same Manifest → the same bytes.
 */
export function renderBrainWorkspace(manifest) {
  assertBrainManifest(manifest);
  const known = new Set(manifest.sources.map((source) => source.path));
  const e = manifest.entities;

  const contents = {
    Home: renderHome(manifest, known),
    Sessions: renderSessions(manifest),
    Decisions: renderIndex('Decisions', 'Index', 'Index of decision entries recorded in the project. Each entry links to its source; content is not copied.', e.decisions, EMPTY.decisions, known),
    Risks: renderIndex('Risks', 'Index', 'Index of risk entries recorded in the project. Each entry links to its source; content is not copied.', e.risks, EMPTY.risks, known),
    Bugs: renderIndex('Bugs', 'Open Bugs', 'Open bugs aggregated across sessions. Each entry links to its source; content is not copied.', e.open_bugs, EMPTY.bugs, known),
    Releases: renderIndex('Releases', 'Release State', 'Release information carried by the Manifest.', e.release_state, EMPTY.release, known),
    'Recent-Activity': renderRecentActivity(manifest, known),
  };

  const files = VIEW_NAMES
    .map((name) => Object.freeze({ path: `${BRAIN_DIR}/${name}.md`, content: contents[name] }))
    .sort((a, b) => compareStrings(a.path, b.path));
  return Object.freeze(files);
}
