import fs from 'node:fs';
import path from 'node:path';
import { stableStringify } from '../context/fingerprint.js';

// Brain Writer — the filesystem trust boundary of the Project Brain
// (Bloco 08, Fase B). It receives a finished build plan
// (`{ manifest, files }`) and materialises exactly two kinds of output:
//
//   DDAE-Brain/<Name>.md            human views (generated, disposable)
//   .ddae/brain/manifest.json       machine state (written last)
//
// It discovers nothing, compiles nothing, renders nothing and validates the
// Manifest semantically not at all: the upstream layers did that. It does
// not trust them either — "validated upstream" is not permission to write
// anywhere. Every target is re-checked here, and the WHOLE plan is
// preflighted before the first modification (creating a directory already
// counts as one): any failure means zero writes.
//
// Policy (see Bloco 08, Seção 32):
//   - path grammar: `DDAE-Brain/` + exactly one basename ending in `.md`;
//     no controls/DEL/NUL, no `\`, `/`, `:`, `*`, `?`, `"`, `<`, `>`, `|`, no
//     lone surrogates, no leading dot, no Windows reserved device names, at
//     most 200 UTF-8 bytes. Spaces and ordinary Unicode are fine.
//   - symlinks/junctions anywhere on the write path are refused, fail-closed.
//   - ownership: an existing view is overwritten only if it carries the
//     generated marker right after its H1; `force` waives that and nothing
//     else.
//   - no deletion, ever: extra generated files are only reported.
//   - each file is written to a sibling temp file and renamed onto the
//     target; the manifest goes last, so a failure never claims a new state.
//
// Known limit (TOCTOU): preflight + lstat re-checks + temp/rename is a v1
// defence, not a proof against a concurrent attacker who can swap a
// directory for a symlink between the last check and the write. It also does
// not make the multi-file build transactional: a failure after some views
// were replaced leaves those views new and the manifest old — detectable and
// repaired by running the build again.

export const MANIFEST_OUTPUT_PATH = '.ddae/brain/manifest.json';

// Duplicated on purpose from the producers: the Writer is the last barrier
// and must not depend on (or be redirected by) the modules it guards against.
const VIEWS_DIR = 'DDAE-Brain';
const MANIFEST_DIR_SEGMENTS = Object.freeze(['.ddae', 'brain']);
const MARKER = '_Generated by DDAE. Derived from Docs/ and Git. Do not edit directly._';
const MAX_NAME_BYTES = 200;
const HEAD_BYTES = 4096;

const INVALID_NAME_CHARS = /[\u0000-\u001f\u007f<>:"|?*\\/]/;
const LONE_SURROGATE = /[\ud800-\udbff](?![\udc00-\udfff])|(?<![\ud800-\udbff])[\udc00-\udfff]/;
const RESERVED_DEVICE = /^(con|prn|aux|nul|com[1-9]|lpt[1-9])$/i;

/** Failure of a Writer invariant. `code` is machine-readable; `details` carries only safe relative paths/indexes, never content or the absolute root. */
export class BrainWriterError extends Error {
  constructor(code, message, details = {}) {
    super(`writeBrainWorkspace: ${code}: ${message}`);
    this.name = 'BrainWriterError';
    this.code = code;
    this.details = Object.freeze({ ...details });
  }
}

let tempCounter = 0;

function isPlainObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

const compare = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

// ───────────────────────── input ─────────────────────────

function readInput(plan, options) {
  if (!isPlainObject(plan) || !isPlainObject(plan.manifest) || !Array.isArray(plan.files)) {
    throw new BrainWriterError('INPUT_INVALID', 'plan must be { manifest: object, files: [{ path, content }] }');
  }
  if (options !== undefined && !isPlainObject(options)) {
    throw new BrainWriterError('INPUT_INVALID', 'options must be an object when provided');
  }
  const force = options?.force ?? false;
  if (typeof force !== 'boolean') {
    throw new BrainWriterError('INPUT_INVALID', 'options.force must be a boolean');
  }
  plan.files.forEach((entry, index) => {
    if (!isPlainObject(entry) || typeof entry.path !== 'string' || typeof entry.content !== 'string') {
      throw new BrainWriterError('INPUT_INVALID', 'each file must be { path: string, content: string }', { index });
    }
  });
  let manifestText;
  try {
    manifestText = `${stableStringify(plan.manifest)}\n`;
  } catch {
    throw new BrainWriterError('INPUT_INVALID', 'manifest could not be serialized canonically');
  }
  return { files: plan.files, force, manifestText };
}

function resolveProjectRoot(projectRoot) {
  if (typeof projectRoot !== 'string' || projectRoot === '') {
    throw new BrainWriterError('PROJECT_ROOT_INVALID', 'projectRoot must be a non-empty path string');
  }
  try {
    const real = fs.realpathSync(path.resolve(projectRoot));
    if (!fs.statSync(real).isDirectory()) {
      throw new Error('not a directory');
    }
    return real;
  } catch {
    throw new BrainWriterError('PROJECT_ROOT_INVALID', 'projectRoot does not exist or is not a directory');
  }
}

// ───────────────────────── path policy ─────────────────────────

/** The human-view grammar; returns the basename when `outputPath` satisfies it, otherwise `null`. */
function viewBasename(outputPath) {
  const prefix = `${VIEWS_DIR}/`;
  if (!outputPath.startsWith(prefix)) {
    return null;
  }
  const name = outputPath.slice(prefix.length);
  if (!name.endsWith('.md') || name.length <= '.md'.length || name.startsWith('.')) {
    return null;
  }
  if (Buffer.byteLength(name, 'utf8') > MAX_NAME_BYTES || INVALID_NAME_CHARS.test(name) || LONE_SURROGATE.test(name)) {
    return null;
  }
  const stem = name.split('.')[0].replace(/ +$/, '');
  return RESERVED_DEVICE.test(stem) ? null : name;
}

/** Ownership signal: the generated marker exactly where the views put it — after the H1, separated by one blank line. */
function hasOwnershipMarker(text) {
  const lines = text.replace(/\r\n/g, '\n').split('\n', 3);
  return lines.length === 3 && lines[0].startsWith('# ') && lines[1] === '' && lines[2] === MARKER;
}

function checkPlanShape(files) {
  const exact = new Set();
  const folded = new Map();
  const views = files.map((entry, index) => {
    const name = viewBasename(entry.path);
    if (name === null) {
      throw new BrainWriterError('OUTPUT_PATH_INVALID', 'output path is not an allowed human view path', { index });
    }
    if (!hasOwnershipMarker(entry.content)) {
      throw new BrainWriterError('OUTPUT_CONTENT_INVALID', 'a view must carry the generated marker after its H1, or it could never be owned again', { index, path: entry.path });
    }
    if (exact.has(entry.path)) {
      throw new BrainWriterError('OUTPUT_DUPLICATE', 'the same output path appears more than once', { index, path: entry.path });
    }
    exact.add(entry.path);
    const key = entry.path.toLowerCase();
    if (folded.has(key)) {
      throw new BrainWriterError('OUTPUT_CASE_COLLISION', 'two output paths differ only by case', { index, path: entry.path, other: folded.get(key) });
    }
    folded.set(key, entry.path);
    return { rel: entry.path, name, content: Buffer.from(entry.content, 'utf8') };
  });
  return views.sort((a, b) => compare(a.rel, b.rel));
}

// ───────────────────────── filesystem inspection ─────────────────────────

function lstatOrNull(absolute, rel) {
  try {
    return fs.lstatSync(absolute);
  } catch (cause) {
    if (cause?.code === 'ENOENT' || cause?.code === 'ENOTDIR') {
      return null;
    }
    throw new BrainWriterError('WRITE_FAILED', 'could not inspect an output location', { path: rel, system_code: String(cause?.code ?? '') });
  }
}

/** A directory the Writer writes into must be a real directory (or absent): never a symlink/junction, never a file. */
function assertRealDirectory(root, segments) {
  const rel = segments.join('/');
  const stat = lstatOrNull(path.join(root, ...segments), rel);
  if (stat === null) {
    return false;
  }
  if (stat.isSymbolicLink()) {
    throw new BrainWriterError('SYMLINK_REFUSED', 'an output directory is a symbolic link or junction', { path: rel });
  }
  if (!stat.isDirectory()) {
    throw new BrainWriterError('TARGET_TYPE_INVALID', 'an output directory exists but is not a directory', { path: rel });
  }
  return true;
}

function assertDirectoryChain(root, segments) {
  for (let depth = 1; depth <= segments.length; depth += 1) {
    if (!assertRealDirectory(root, segments.slice(0, depth))) {
      return;
    }
  }
}

/** Classifies one target: `create`, `unchanged`, or `replace` (with the existing bytes when relevant). */
function inspectTarget(root, rel, content) {
  const absolute = path.join(root, ...rel.split('/'));
  const stat = lstatOrNull(absolute, rel);
  if (stat === null) {
    return { state: 'create' };
  }
  if (stat.isSymbolicLink()) {
    throw new BrainWriterError('SYMLINK_REFUSED', 'an output target is a symbolic link', { path: rel });
  }
  if (!stat.isFile()) {
    throw new BrainWriterError('TARGET_TYPE_INVALID', 'an output target exists but is not a regular file', { path: rel });
  }
  let existing;
  try {
    existing = fs.readFileSync(absolute);
  } catch (cause) {
    throw new BrainWriterError('WRITE_FAILED', 'could not read an existing output target', { path: rel, system_code: String(cause?.code ?? '') });
  }
  return existing.equals(content) ? { state: 'unchanged' } : { state: 'replace', existing };
}

function readHead(absolute, rel) {
  let fd = null;
  try {
    fd = fs.openSync(absolute, 'r');
    const buffer = Buffer.alloc(HEAD_BYTES);
    const read = fs.readSync(fd, buffer, 0, HEAD_BYTES, 0);
    return buffer.subarray(0, read).toString('utf8');
  } catch (cause) {
    throw new BrainWriterError('WRITE_FAILED', 'could not read a generated-file candidate', { path: rel, system_code: String(cause?.code ?? '') });
  } finally {
    if (fd !== null) {
      try { fs.closeSync(fd); } catch { /* nothing to recover */ }
    }
  }
}

/** Generated views on disk that the current plan no longer declares — reported, never touched (D7). */
function findStaleGenerated(root, plannedFolded) {
  const dir = path.join(root, VIEWS_DIR);
  let names;
  try {
    names = fs.readdirSync(dir);
  } catch (cause) {
    if (cause?.code === 'ENOENT') {
      return [];
    }
    throw new BrainWriterError('WRITE_FAILED', 'could not list the views directory', { path: VIEWS_DIR, system_code: String(cause?.code ?? '') });
  }
  const stale = [];
  for (const name of names.sort(compare)) {
    const rel = `${VIEWS_DIR}/${name}`;
    if (!name.endsWith('.md') || plannedFolded.has(rel.toLowerCase())) {
      continue;
    }
    const stat = lstatOrNull(path.join(dir, name), rel);
    if (stat === null || stat.isSymbolicLink() || !stat.isFile()) {
      continue;
    }
    if (hasOwnershipMarker(readHead(path.join(dir, name), rel))) {
      stale.push(rel);
    }
  }
  return stale;
}

// ───────────────────────── writing ─────────────────────────

function ensureRealDirectory(root, segments) {
  if (!assertRealDirectory(root, segments)) {
    try {
      fs.mkdirSync(path.join(root, ...segments));
    } catch (cause) {
      if (cause?.code !== 'EEXIST') {
        throw new BrainWriterError('WRITE_FAILED', 'could not create an output directory', { path: segments.join('/'), system_code: String(cause?.code ?? '') });
      }
    }
    assertRealDirectory(root, segments);
  }
}

function atomicWrite(root, directorySegments, rel, content, written) {
  ensureRealDirectory(root, directorySegments);
  const target = path.join(root, ...rel.split('/'));
  const temp = `${target}.tmp-${process.pid}-${tempCounter}`;
  tempCounter += 1;
  let fd = null;
  let created = false;
  try {
    fd = fs.openSync(temp, 'wx', 0o644);
    created = true;
    fs.writeFileSync(fd, content);
    fs.fsyncSync(fd);
    fs.closeSync(fd);
    fd = null;
    fs.renameSync(temp, target);
  } catch (cause) {
    if (fd !== null) {
      try { fs.closeSync(fd); } catch { /* keep the original error */ }
    }
    if (created) {
      try { fs.unlinkSync(temp); } catch { /* keep the original error */ }
    }
    throw new BrainWriterError('WRITE_FAILED', 'could not write an output file', {
      path: rel,
      system_code: String(cause?.code ?? ''),
      written: Object.freeze([...written]),
    });
  }
  written.push(rel);
}

/**
 * Materialises a build plan under `projectRoot`.
 *
 * @param {string} projectRoot  an existing directory (never created here)
 * @param {{ manifest: object, files: { path: string, content: string }[] }} plan
 * @param {{ force?: boolean }} [options]  `force` waives ONLY an ownership conflict on an existing, unmarked view
 * @returns {{ written: string[], unchanged: string[], stale_generated: string[] }} frozen, sorted,
 *          project-relative report — no content. Throws `BrainWriterError` (stable `code`); on any
 *          preflight failure nothing was written.
 */
export function writeBrainWorkspace(projectRoot, plan, options) {
  const { files, force, manifestText } = readInput(plan, options);
  const root = resolveProjectRoot(projectRoot);
  const views = checkPlanShape(files);

  // ── preflight: read-only, complete, before the first modification ──
  assertDirectoryChain(root, [VIEWS_DIR]);
  assertDirectoryChain(root, MANIFEST_DIR_SEGMENTS);

  const viewWork = views.map((view) => {
    const inspected = inspectTarget(root, view.rel, view.content);
    if (inspected.state === 'replace' && !force && !hasOwnershipMarker(inspected.existing.toString('utf8'))) {
      throw new BrainWriterError('OWNERSHIP_CONFLICT', 'an existing file at this path was not generated by DDAE', { path: view.rel });
    }
    return { ...view, state: inspected.state };
  });
  const manifestContent = Buffer.from(manifestText, 'utf8');
  const manifestState = inspectTarget(root, MANIFEST_OUTPUT_PATH, manifestContent).state;
  const stale = findStaleGenerated(root, new Set(views.map((view) => view.rel.toLowerCase())));

  // ── writes: views first (sorted), the manifest strictly last ──
  const written = [];
  for (const view of viewWork) {
    if (view.state !== 'unchanged') {
      atomicWrite(root, [VIEWS_DIR], view.rel, view.content, written);
    }
  }
  if (manifestState !== 'unchanged') {
    ensureRealDirectory(root, MANIFEST_DIR_SEGMENTS.slice(0, 1));
    atomicWrite(root, MANIFEST_DIR_SEGMENTS, MANIFEST_OUTPUT_PATH, manifestContent, written);
  }

  const unchanged = [
    ...viewWork.filter((view) => view.state === 'unchanged').map((view) => view.rel),
    ...(manifestState === 'unchanged' ? [MANIFEST_OUTPUT_PATH] : []),
  ];
  return Object.freeze({
    written: Object.freeze(written.sort(compare)),
    unchanged: Object.freeze(unchanged.sort(compare)),
    stale_generated: Object.freeze(stale.sort(compare)),
  });
}
